### ISSUE TITLE
[BUG] Crash on Server

### ISSUE THREAD

**Issue by GazbonicAcid** [BeardlessBrady/Currency-Mod#1]
Good Ol' Currency causes a crash on servers.
[console_log.txt](https://github.com/BeardlessBrady/Currency-Mod/files/619631/crash_log.txt)
[crash-2016-11-29_10.58.00-server.txt](https://github.com/BeardlessBrady/Currency-Mod/files/619638/crash-2016-11-29_10.58.00-server.txt)

**Comment by Beardlessbrady** [comment]
I completely forget to test the server side of things, fixed in next release
