### ISSUE TITLE
[Bug] Price display tooltip does not show up

### ISSUE THREAD

**Issue by GazbonicAcid** [BeardlessBrady/Currency-Mod#10]
The tooltip for showing the vending machine buyer and exchange machine seller the price per item currently does not appear at all.

**Comment by Beardlessbrady** [comment]
Works for me on the latest version 
![untitled](https://cloud.githubusercontent.com/assets/3486400/21444913/e5ec745a-c880-11e6-9e10-b890595b4648.png)

**Comment by GazbonicAcid** [comment]
I might not have been seeing it because of debug mode tooltips being on.
I'll screenshot proof they don't show with debug mode on,
as well as seeing if it was indeed debug mode hiding it.
Probably was, but at least you can test it on your end if debug mode (F3+H) tooltips hide it.

**Comment by Beardlessbrady** [comment]
Didnt even know debug mode is a thing. But it still seems to work for me

**Comment by GazbonicAcid** [comment]
Well it must be something on my end, such as a mod incompatibility.
[Tooltip with advanced/debug tooltips on](http://i.imgur.com/cWQDqzA.png)
[Tooltip with it off](http://i.imgur.com/ZMK7pH1.png)
[ATLauncher Console Log](https://hastebin.com/itetodicin.md)
[Logs Again.zip](https://github.com/BeardlessBrady/Currency-Mod/files/670266/Logs.Again.zip)

**Comment by GazbonicAcid** [comment]
Looking at my ATLauncher Console Log again it may have been an incompatibility with the Waystones mod.
I'll remove it from my pack dev instance and try again.

**Comment by Beardlessbrady** [comment]
What is the specific modpack you are using?

**Comment by Beardlessbrady** [comment]
?

**Comment by GazbonicAcid** [comment]
The one I'm the founder/author/owner of, [Township Farms](https://www.atlauncher.com/pack/TownshipFarms/).

**Comment by GazbonicAcid** [comment]
My curse name is Valorn_Exhio, and Township Farms is the modpack I told you about when I asked on the curseforge comments about adding it to my pack.

**Comment by Beardlessbrady** [comment]
Oh Right. Your Github name is different so I didn't realize

**Comment by Beardlessbrady** [comment]
Alright I will isolate the issue and add a bugfix for next release (coming in the next few days)

**Comment by Beardlessbrady** [comment]
I believe it is NEI. Weird how NEI requires JEI. seems redundant. What are the pros of using NEI over JEI?
Anywho Ill see if I can fix this

**Comment by GazbonicAcid** [comment]
The 1.10.2 NEI is an addon to JEI, and not made (but authorized) by the original NEI's author.
I'd prefer the FEI addon, but it adds a bug to the JEI search bar.
I have NEI because it adds the creative plus mode from the original NEI by ChickenBones back into MC.

**Comment by Beardlessbrady** [comment]
Interesting, Ill see what I can do

**Comment by Beardlessbrady** [comment]
I posted an issue on the NEI Github. Hopefully they will know how to fix this

**Comment by Beardlessbrady** [comment]
Ya it seems to be an issue on their end. Not much more I can
