### ISSUE TITLE
Vending machine makes the world disappear

### ISSUE THREAD

**Issue by Nekkkk** [BeardlessBrady/Currency-Mod#103]
Hello, I was testing out this mod and found a bug.

Whenever I open the vending machine, the whole world glitches and sort of disappears
[https://imgur.com/a/9jhutLX](https://imgur.com/a/9jhutLX)

I have Optifine and BetterFPS installed. I've noticed that when I change the graphics settings from Fast to Fancy, the world glitches only when I open the vending machine's UI.

Edit : I tested without Optifine and the issue is gone, so the issue probably comes from Optifne. Thing is, I need Optifine for my FPSs.

**Comment by Beardlessbrady** [comment]
Optifine breaks many many things so there is not much I can do, Sorry
