### ISSUE TITLE
Crash when editing items

### ISSUE THREAD

**Issue by FluffiKiki** [BeardlessBrady/Currency-Mod#105]
In the alpha version 20200311, the trade-in and vending machines will crash if I try to edit an item from within them. It happens when I click on an item after placing it in the machines to edit their prices. Here is my latest crash report (it was done on a tester instance, which is why there are a few mods)

---- Minecraft Crash Report ----

WARNING: coremods are present:
  OTGCorePlugin (OTG-Core.jar)
Contact their authors BEFORE contacting forge

// You should try our sister game, Minceraft!

Time: 3/12/20 12:26 PM
Description: Rendering screen

java.lang.NoSuchMethodError: net.minecraft.item.Item.getForgeRarity(Lnet/minecraft/item/ItemStack;)Lnet/minecraftforge/common/IRarity;
	at beardlessbrady.modcurrency.block.tradein.GuiTradein.func_146285_a(GuiTradein.java:386)
	at net.minecraft.client.gui.inventory.GuiContainer.func_191948_b(GuiContainer.java:175)
	at beardlessbrady.modcurrency.block.tradein.GuiTradein.func_73863_a(GuiTradein.java:115)
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:381)
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1124)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1118)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:397)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at beardlessbrady.modcurrency.block.tradein.GuiTradein.func_146285_a(GuiTradein.java:386)
	at net.minecraft.client.gui.inventory.GuiContainer.func_191948_b(GuiContainer.java:175)
	at beardlessbrady.modcurrency.block.tradein.GuiTradein.func_73863_a(GuiTradein.java:115)
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:381)

-- Screen render details --
Details:
	Screen name: beardlessbrady.modcurrency.block.tradein.GuiTradein
	Mouse location: Scaled: (198, 36). Absolute: (794, 856)
	Screen size: Scaled: (480, 251). Absolute: (1920, 1001). Scale factor of 4

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityPlayerSP['FluffiKiki'/31, l='MpServer', x=57.18, y=5.00, z=168.49]]
	Chunk stats: MultiplayerChunkCache: 624, 624
	Level seed: 0
	Level generator: ID 01 - flat, ver 0. Features enabled: false
	Level generator options: 
	Level spawn location: World: (142,4,315), Chunk: (at 14,0,11 in 8,19; contains blocks 128,0,304 to 143,255,319), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 4680 game time, 4680 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
	Forced entities: 99 total; [EntityVillager['Villager'/0, l='MpServer', x=40.20, y=3.94, z=196.56], EntityVillager['Villager'/1, l='MpServer', x=36.30, y=4.00, z=200.38], EntityVillager['Villager'/2, l='MpServer', x=19.59, y=4.00, z=191.64], EntityVillager['Villager'/3, l='MpServer', x=28.47, y=5.00, z=193.89], EntityVillager['Villager'/4, l='MpServer', x=43.86, y=3.94, z=195.30], EntitySlime['Slime'/879625, l='MpServer', x=-17.49, y=4.00, z=243.00], EntityVillager['Villager'/5, l='MpServer', x=59.59, y=4.00, z=177.70], EntityItem['item.item.slimeball'/823561, l='MpServer', x=60.33, y=4.00, z=175.75], EntityVillager['Villager'/6, l='MpServer', x=48.51, y=4.00, z=157.69], EntityVillager['Villager'/7, l='MpServer', x=62.73, y=4.00, z=174.67], EntityVillager['Villager'/8, l='MpServer', x=53.50, y=3.94, z=167.32], EntityVillager['Villager'/9, l='MpServer', x=39.50, y=4.00, z=185.37], EntityVillager['Villager'/10, l='MpServer', x=38.98, y=5.00, z=197.54], EntityVillager['Villager'/11, l='MpServer', x=49.70, y=5.00, z=204.30], EntitySlime['Slime'/805127, l='MpServer', x=75.86, y=4.14, z=242.93], EntityItem['item.item.potato'/846599, l='MpServer', x=60.46, y=5.00, z=221.16], EntitySlime['Slime'/836103, l='MpServer', x=-21.65, y=4.00, z=226.07], EntityVillager['Villager'/12, l='MpServer', x=44.45, y=5.00, z=223.27], EntityVillager['Villager'/13, l='MpServer', x=56.06, y=4.94, z=217.85], EntityVillager['Villager'/14, l='MpServer', x=82.97, y=4.00, z=209.64], EntityVillager['Villager'/15, l='MpServer', x=49.25, y=5.25, z=191.59], EntityVillager['Villager'/16, l='MpServer', x=59.51, y=4.00, z=209.39], EntityVillager['Villager'/17, l='MpServer', x=54.74, y=5.00, z=217.37], EntityItem['item.item.seeds'/569113, l='MpServer', x=48.72, y=4.00, z=170.13], EntityVillager['Villager'/18, l='MpServer', x=71.59, y=5.00, z=215.74], EntityVillager['Villager'/19, l='MpServer', x=64.51, y=5.00, z=217.43], EntityVillager['Villager'/20, l='MpServer', x=76.54, y=3.94, z=202.30], EntityVillager['Villager'/21, l='MpServer', x=78.74, y=5.00, z=204.55], EntityVillager['Villager'/22, l='MpServer', x=86.40, y=5.00, z=221.45], EntityItem['item.item.slimeball'/838938, l='MpServer', x=60.82, y=4.00, z=170.52], EntityVillager['Villager'/23, l='MpServer', x=75.50, y=4.00, z=227.34], EntityVillager['Villager'/24, l='MpServer', x=88.50, y=4.00, z=218.67], EntityVillager['Villager'/25, l='MpServer', x=94.44, y=4.00, z=222.87], EntitySlime['Slime'/728082, l='MpServer', x=71.98, y=4.28, z=233.14], EntityVillager['Villager'/26, l='MpServer', x=82.30, y=4.00, z=229.60], EntityVillager['Villager'/27, l='MpServer', x=103.83, y=3.94, z=224.22], EntityVillager['Villager'/28, l='MpServer', x=96.72, y=4.00, z=230.52], EntityVillager['Villager'/29, l='MpServer', x=95.02, y=4.94, z=203.67], EntityVillager['Villager'/30, l='MpServer', x=95.31, y=4.00, z=205.72], EntitySheep['Sheep'/73503, l='MpServer', x=6.37, y=4.00, z=127.20], EntitySlime['Slime'/789266, l='MpServer', x=47.28, y=4.00, z=110.05], EntitySheep['Sheep'/73502, l='MpServer', x=12.22, y=4.00, z=123.76], EntitySheep['Sheep'/73505, l='MpServer', x=2.50, y=4.00, z=127.50], EntitySheep['Sheep'/73504, l='MpServer', x=6.50, y=4.00, z=129.50], EntitySlime['Slime'/396583, l='MpServer', x=125.50, y=4.00, z=94.90], EntityItem['item.item.slimeball'/818734, l='MpServer', x=60.14, y=4.00, z=173.04], EntitySlime['Slime'/186657, l='MpServer', x=46.06, y=5.17, z=201.98], EntityChicken['Chicken'/73509, l='MpServer', x=136.50, y=4.00, z=205.50], EntitySheep['Sheep'/73511, l='MpServer', x=76.78, y=4.00, z=116.51], EntityChicken['Chicken'/73510, l='MpServer', x=58.78, y=4.00, z=105.55], EntitySheep['Sheep'/73513, l='MpServer', x=67.89, y=4.00, z=111.09], EntitySheep['Sheep'/73512, l='MpServer', x=59.36, y=4.00, z=106.82], EntityPig['Pig'/73515, l='MpServer', x=87.22, y=4.00, z=176.64], EntityPig['Pig'/73514, l='MpServer', x=83.16, y=4.00, z=180.60], EntityPig['Pig'/73517, l='MpServer', x=82.53, y=4.00, z=145.71], EntitySlime['Slime'/478251, l='MpServer', x=49.45, y=5.75, z=221.74], EntitySlime['Slime'/919586, l='MpServer', x=7.84, y=4.00, z=163.11], EntityPig['Pig'/73516, l='MpServer', x=74.67, y=4.00, z=164.79], EntitySlime['Slime'/658980, l='MpServer', x=78.41, y=4.00, z=97.41], EntitySlime['Slime'/734500, l='MpServer', x=102.63, y=4.42, z=220.97], EntityCow['Cow'/73520, l='MpServer', x=-19.82, y=4.00, z=172.39], EntitySlime['Slime'/791869, l='MpServer', x=60.31, y=4.28, z=237.61], EntityCow['Cow'/73523, l='MpServer', x=-17.50, y=4.00, z=162.50], EntityItem['item.item.slimeball'/704830, l='MpServer', x=52.38, y=3.94, z=175.93], EntitySlime['Slime'/899387, l='MpServer', x=58.12, y=9.00, z=207.88], EntitySlime['Slime'/755504, l='MpServer', x=69.65, y=4.33, z=112.74], EntitySlime['Slime'/558664, l='MpServer', x=-17.57, y=4.92, z=216.40], EntitySlime['Slime'/876872, l='MpServer', x=70.66, y=4.00, z=104.63], EntityIronGolem['Iron Golem'/359235, l='MpServer', x=63.13, y=4.00, z=172.13], EntitySlime['Slime'/836164, l='MpServer', x=129.57, y=4.00, z=235.14], EntityHorse['Horse'/73555, l='MpServer', x=-5.94, y=4.00, z=158.65], EntityHorse['Horse'/73554, l='MpServer', x=-4.61, y=4.00, z=155.17], EntitySlime['Slime'/884318, l='MpServer', x=7.41, y=4.00, z=175.52], EntitySheep['Sheep'/73557, l='MpServer', x=-2.50, y=4.00, z=154.50], EntitySheep['Sheep'/73558, l='MpServer', x=-5.98, y=4.00, z=153.74], EntityHorse['Horse'/73563, l='MpServer', x=81.50, y=4.00, z=244.50], EntityChicken['Chicken'/73562, l='MpServer', x=79.50, y=4.00, z=240.50], EntitySheep['Sheep'/73565, l='MpServer', x=76.93, y=4.00, z=240.08], EntityItem['item.item.potato'/289625, l='MpServer', x=61.39, y=4.94, z=220.62], EntityHorse['Horse'/73564, l='MpServer', x=85.54, y=4.00, z=242.31], EntityItem['item.item.slimeball'/884854, l='MpServer', x=62.45, y=4.00, z=170.20], EntityPlayerSP['FluffiKiki'/31, l='MpServer', x=57.18, y=5.00, z=168.49], EntitySlime['Slime'/919179, l='MpServer', x=9.05, y=4.00, z=169.33], EntitySlime['Slime'/80778, l='MpServer', x=58.32, y=5.02, z=160.37], EntitySlime['Slime'/731031, l='MpServer', x=62.35, y=5.00, z=220.90], EntitySlime['Slime'/887699, l='MpServer', x=58.42, y=4.00, z=244.83], EntityItem['item.item.slimeball'/863122, l='MpServer', x=63.79, y=4.00, z=171.45], EntitySlime['Slime'/97446, l='MpServer', x=78.00, y=4.94, z=140.61], EntitySlime['Slime'/605858, l='MpServer', x=55.88, y=4.00, z=118.97], EntitySlime['Slime'/924069, l='MpServer', x=-3.92, y=4.95, z=242.93], EntitySlime['Slime'/906402, l='MpServer', x=55.25, y=5.00, z=208.25], EntitySlime['Slime'/726195, l='MpServer', x=74.94, y=4.00, z=101.26], EntityItem['item.item.potato'/260545, l='MpServer', x=59.39, y=5.00, z=220.18], EntitySlime['Slime'/789729, l='MpServer', x=103.67, y=4.08, z=126.62], EntityItem['item.item.seeds'/582630, l='MpServer', x=47.43, y=4.00, z=170.88], EntityIronGolem['Iron Golem'/440052, l='MpServer', x=64.79, y=4.00, z=170.79], EntityItem['item.item.seeds'/456692, l='MpServer', x=66.85, y=4.94, z=133.43], EntityItem['item.item.slimeball'/711926, l='MpServer', x=51.73, y=3.94, z=174.35], EntityItem['item.item.seeds'/407545, l='MpServer', x=71.62, y=5.00, z=133.78]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:420)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2740)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:418)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_231, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 817375216 bytes (779 MB) / 1393557504 bytes (1329 MB) up to 2386558976 bytes (2276 MB)
	JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms512m -Xmx2560m
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2772 9 mods loaded, 9 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State     | ID            | Version                     | Source                                        | Signature                                |
	|:--------- |:------------- |:--------------------------- |:--------------------------------------------- |:---------------------------------------- |
	| UCHIJAAAA | minecraft     | 1.12.2                      | minecraft.jar                                 | None                                     |
	| UCHIJAAAA | mcp           | 9.42                        | minecraft.jar                                 | None                                     |
	| UCHIJAAAA | FML           | 8.0.99.99                   | forge-1.12.2-14.23.5.2772-universal.jar       | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJAAAA | forge         | 14.23.5.2772                | forge-1.12.2-14.23.5.2772-universal.jar       | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJAAAA | otgcore       | 1.12.2 - v8_r8              | minecraft.jar                                 | None                                     |
	| UCHIJAAAA | biomesoplenty | 7.0.1.2350                  | BiomesOPlenty-1.12.2-7.0.1.2350-universal.jar | None                                     |
	| UCHIJAAAA | modcurrency   | 1.12.0-2.0.0-ALPHA-20200311 | Currency-1.12.0-2.0.0-ALPHA-20200311.jar      | None                                     |
	| UCHIJAAAA | jei           | 4.13.1.225                  | jei_1.12.2-4.13.1.225.jar                     | None                                     |
	| UCHIJAAAA | worldedit     | 6.1.8                       | worldedit-forge-mc1.12-6.1.8-dist.jar         | None                                     |

	Loaded coremods (and transformers): 
OTGCorePlugin (OTG-Core.jar)
  com.pg85.otg.forge.asm.excluded.OTGClassTransformer
	GL info: ' Vendor: 'Intel' Version: '4.5.0 - Build 24.20.100.6025' Renderer: 'Intel(R) HD Graphics 620'
	Launched Version: MultiMC5
	LWJGL: 2.9.4
	OpenGL: Intel(R) HD Graphics 620 GL version 4.5.0 - Build 24.20.100.6025, Intel
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 4x Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz

**Comment by Beardlessbrady** [comment]
This seems to be an issue with the version of forge you are using. I am currently building the mod on 1.12.2 - 14.23.5.2847. Change your forge to that version and see if that fixes it. If this causes issues with other mods let me know and Ill build the mod on whatever version works for you.

**Comment by FluffiKiki** [comment]
Ah, that makes sense. I can't use Forge 1.12 past 14.23.5.2772 because it breaks mods built <.2768 or MCreator mods. No need to make another build, since I've observed that people have updated from then. Thanks for letting me know! (Feel free to close if you feel this is resolved)
