### ISSUE TITLE
Crash Frequently

### ISSUE THREAD

**Issue by Kozmito** [BeardlessBrady/Currency-Mod#106]
Hello, every time that I put a vending machine, Minecraft crashes. Here is the crash report. Also, im using the new alpha version.

---- Minecraft Crash Report ----

WARNING: coremods are present:
Contact their authors BEFORE contacting forge

// I bet Cylons wouldn't have this problem.

Time: 3/16/20 3:16 PM
Description: Rendering Block Entity

java.lang.NullPointerException: Rendering Block Entity
	at beardlessbrady.modcurrency.block.vending.RenderVending.render(RenderVending.java:31)
	at beardlessbrady.modcurrency.block.vending.RenderVending.func_192841_a(RenderVending.java:24)
	at net.minecraft.client.renderer.tileentity.TileEntityRendererDispatcher.func_192854_a(TileEntityRendererDispatcher.java:201)
	at net.minecraft.client.renderer.tileentity.TileEntityRendererDispatcher.func_180546_a(TileEntityRendererDispatcher.java:157)
	at net.minecraft.client.renderer.RenderGlobal.func_180446_a(RenderGlobal.java:1032)
	at net.minecraft.client.renderer.EntityRenderer.func_175068_a(EntityRenderer.java:1801)
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1614)
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1385)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1119)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:398)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at beardlessbrady.modcurrency.block.vending.RenderVending.render(RenderVending.java:31)
	at beardlessbrady.modcurrency.block.vending.RenderVending.func_192841_a(RenderVending.java:24)

-- Block Entity Details --
Details:
	Name: modcurrency:blockvending_te // beardlessbrady.modcurrency.block.vending.TileVending
	Block type: ID #491 (tile.modcurrency:blockvending // beardlessbrady.modcurrency.block.vending.BlockVending // modcurrency:blockvending)
	Block data value: 4 / 0x4 / 0b0100
	Block location: World: (269,63,153), Chunk: (at 13,3,9 in 16,9; contains blocks 256,0,144 to 271,255,159), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Actual block type: ID #491 (tile.modcurrency:blockvending // beardlessbrady.modcurrency.block.vending.BlockVending // modcurrency:blockvending)
	Actual block data value: 4 / 0x4 / 0b0100
Stacktrace:
	at net.minecraft.client.renderer.tileentity.TileEntityRendererDispatcher.func_192854_a(TileEntityRendererDispatcher.java:201)
	at net.minecraft.client.renderer.tileentity.TileEntityRendererDispatcher.func_180546_a(TileEntityRendererDispatcher.java:157)
	at net.minecraft.client.renderer.RenderGlobal.func_180446_a(RenderGlobal.java:1032)
	at net.minecraft.client.renderer.EntityRenderer.func_175068_a(EntityRenderer.java:1801)
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1614)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityPlayerSP['XbyKosmosGamer'/121979, l='MpServer', x=277.47, y=66.32, z=161.52]]
	Chunk stats: MultiplayerChunkCache: 441, 441
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: World: (196,64,244), Chunk: (at 4,4,4 in 12,15; contains blocks 192,0,240 to 207,255,255), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 2125752 game time, 30832 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Forced entities: 137 total; [EntitySkeleton['Esqueleto'/133638, l='MpServer', x=258.50, y=55.00, z=105.50], EntitySkeleton['Esqueleto'/133639, l='MpServer', x=260.50, y=55.00, z=109.50], EntityBat['Murciélago'/133381, l='MpServer', x=338.75, y=44.10, z=194.45], EntitySkeleton['Esqueleto'/131594, l='MpServer', x=231.50, y=11.00, z=230.50], EntityPlayerSP['XbyKosmosGamer'/121979, l='MpServer', x=277.47, y=66.32, z=161.52], EntityItem['item.item.egg'/126749, l='MpServer', x=265.98, y=63.00, z=141.01], EntityBat['Murciélago'/129308, l='MpServer', x=287.53, y=46.10, z=166.42], EntityItem['item.item.egg'/130338, l='MpServer', x=267.10, y=63.00, z=126.02], EntitySkeleton['Esqueleto'/123177, l='MpServer', x=285.53, y=64.00, z=169.73], EntitySpider['Araña'/133677, l='MpServer', x=310.50, y=27.00, z=161.50], EntityBat['Murciélago'/133942, l='MpServer', x=309.43, y=57.10, z=232.25], EntityBat['Murciélago'/133943, l='MpServer', x=330.20, y=51.02, z=240.93], EntitySentry['Torreta'/45878, l='MpServer', x=309.50, y=96.00, z=221.50], EntitySquid['Calamar'/125755, l='MpServer', x=240.17, y=59.39, z=166.69], EntityBat['Murciélago'/126523, l='MpServer', x=200.84, y=32.54, z=165.64], EntityItem['item.item.egg'/124732, l='MpServer', x=261.55, y=63.00, z=124.75], EntitySquid['Calamar'/125758, l='MpServer', x=277.60, y=57.00, z=153.60], EntityPig['Cerdo'/34372, l='MpServer', x=299.74, y=63.00, z=100.62], EntitySkeleton['Esqueleto'/133962, l='MpServer', x=325.50, y=20.00, z=108.50], EntityEnderman['Enderman'/134219, l='MpServer', x=233.50, y=70.00, z=97.50], EntityCreeper['Creeper'/122705, l='MpServer', x=270.78, y=59.00, z=135.53], EntityCreeper['Creeper'/134226, l='MpServer', x=237.50, y=70.00, z=98.50], EntitySkeleton['Esqueleto'/133201, l='MpServer', x=331.50, y=33.00, z=165.50], EntityZombie['Zombi'/127321, l='MpServer', x=280.52, y=40.00, z=151.73], EntitySkeleton['Esqueleto'/133464, l='MpServer', x=323.50, y=35.00, z=111.50], EntityOtherPlayerMP['Somoscfug99'/57921, l='MpServer', x=268.50, y=86.15, z=217.04], EntityBat['Murciélago'/122463, l='MpServer', x=272.32, y=54.10, z=180.45], EntitySentry['Torreta'/96, l='MpServer', x=232.50, y=114.00, z=269.50], EntitySkeleton['Esqueleto'/133218, l='MpServer', x=315.50, y=63.00, z=218.50], EntitySentry['Torreta'/97, l='MpServer', x=232.50, y=114.00, z=263.50], EntityBat['Murciélago'/132451, l='MpServer', x=307.25, y=60.10, z=239.75], EntitySentry['Torreta'/98, l='MpServer', x=231.50, y=113.00, z=261.50], EntityCreeper['Creeper'/132710, l='MpServer', x=352.01, y=26.00, z=133.50], EntityCreeper['Creeper'/132709, l='MpServer', x=354.50, y=26.00, z=132.50], EntitySentry['Torreta'/47209, l='MpServer', x=288.50, y=96.00, z=221.50], EntitySentry['Torreta'/106, l='MpServer', x=255.50, y=116.00, z=269.50], EntityOtherPlayerMP['gaeldrb'/126709, l='MpServer', x=134.20, y=6.50, z=303.41], EntityItem['item.item.egg'/130411, l='MpServer', x=268.23, y=63.00, z=135.39], EntitySentry['Torreta'/107, l='MpServer', x=254.50, y=115.00, z=260.50], EntitySentry['Torreta'/108, l='MpServer', x=250.50, y=116.00, z=266.50], EntitySentry['Torreta'/109, l='MpServer', x=248.50, y=116.00, z=263.50], EntityCow['Vaca'/110, l='MpServer', x=264.85, y=63.00, z=125.35], EntitySentry['Torreta'/117358, l='MpServer', x=216.50, y=87.00, z=234.50], EntityChicken['Gallina'/111, l='MpServer', x=261.41, y=63.00, z=125.83], EntityZombie['Zombi'/126062, l='MpServer', x=283.18, y=42.00, z=156.54], EntityChicken['Gallina'/112, l='MpServer', x=261.78, y=63.00, z=141.50], EntityBat['Murciélago'/134258, l='MpServer', x=325.25, y=46.10, z=130.75], EntityChicken['Gallina'/113, l='MpServer', x=266.83, y=63.00, z=124.82], EntityBat['Murciélago'/134259, l='MpServer', x=326.25, y=44.04, z=131.75], EntityChicken['Gallina'/114, l='MpServer', x=261.96, y=63.00, z=126.74], EntityChicken['Gallina'/115, l='MpServer', x=270.51, y=63.00, z=140.17], EntityBat['Murciélago'/134257, l='MpServer', x=327.75, y=44.03, z=128.25], EntitySentry['Torreta'/119925, l='MpServer', x=223.50, y=83.00, z=243.50], EntityChicken['Gallina'/116, l='MpServer', x=271.36, y=63.00, z=125.87], EntityCow['Vaca'/117, l='MpServer', x=263.75, y=63.00, z=125.61], EntityCow['Vaca'/118, l='MpServer', x=261.52, y=63.00, z=129.81], EntityOtherPlayerMP['gaeldrb'/126709, l='MpServer', x=121.73, y=6.25, z=303.24], EntityChicken['Gallina'/119, l='MpServer', x=262.11, y=63.00, z=125.52], EntityChicken['Gallina'/122, l='MpServer', x=263.74, y=63.00, z=136.89], EntityChicken['Gallina'/123, l='MpServer', x=261.49, y=63.00, z=131.91], EntityChicken['Gallina'/124, l='MpServer', x=262.40, y=63.00, z=124.82], EntityChicken['Gallina'/125, l='MpServer', x=261.49, y=63.00, z=126.78], EntityCow['Vaca'/126, l='MpServer', x=266.84, y=63.00, z=135.34], EntityCow['Vaca'/127, l='MpServer', x=264.20, y=63.00, z=141.42], EntityChicken['Gallina'/128, l='MpServer', x=265.82, y=63.00, z=125.50], EntitySkeleton['Esqueleto'/128129, l='MpServer', x=284.31, y=48.18, z=136.90], EntityChicken['Gallina'/129, l='MpServer', x=260.82, y=63.00, z=124.82], EntityChicken['Gallina'/130, l='MpServer', x=264.68, y=63.00, z=134.81], EntityCreeper['Creeper'/133510, l='MpServer', x=264.50, y=52.00, z=88.50], EntityItem['item.item.egg'/134279, l='MpServer', x=262.03, y=63.00, z=135.78], EntitySpider['Araña'/134283, l='MpServer', x=326.50, y=35.00, z=110.50], EntityCreeper['Creeper'/133515, l='MpServer', x=356.50, y=25.00, z=120.50], EntitySentry['Torreta'/46986, l='MpServer', x=288.50, y=97.00, z=205.50], EntitySentry['Torreta'/140, l='MpServer', x=267.50, y=118.00, z=257.50], EntityBat['Murciélago'/130957, l='MpServer', x=315.62, y=52.10, z=232.25], EntityZombie['Zombi'/133006, l='MpServer', x=281.50, y=62.00, z=234.50], EntitySpider['Araña'/134286, l='MpServer', x=324.50, y=35.00, z=111.50], EntitySentry['Torreta'/141, l='MpServer', x=266.50, y=117.00, z=269.50], EntityItem['item.item.egg'/132754, l='MpServer', x=266.69, y=63.00, z=125.22], EntityOtherPlayerMP['gaeldrb'/126709, l='MpServer', x=215.70, y=65.00, z=205.11], EntitySentry['Torreta'/148, l='MpServer', x=275.50, y=118.00, z=258.50], EntitySentry['Torreta'/149, l='MpServer', x=275.50, y=118.00, z=261.50], EntityZombie['Zombi'/123547, l='MpServer', x=281.44, y=63.00, z=135.80], EntityCreeper['Creeper'/134040, l='MpServer', x=292.50, y=50.00, z=198.50], EntitySkeleton['Esqueleto'/134044, l='MpServer', x=332.50, y=40.00, z=120.50], EntityItem['item.tile.securitycraft:reinforcedCobblestone'/127648, l='MpServer', x=275.36, y=62.00, z=158.33], EntitySquid['Calamar'/133025, l='MpServer', x=282.13, y=62.15, z=149.17], EntitySentry['Torreta'/46500, l='MpServer', x=307.50, y=97.00, z=197.50], EntityCreeper['Creeper'/134055, l='MpServer', x=343.50, y=57.00, z=239.50], EntitySentry['Torreta'/47272, l='MpServer', x=288.50, y=96.00, z=216.50], EntityZombie['Zombi'/134314, l='MpServer', x=236.50, y=43.00, z=86.50], EntityCreeper['Creeper'/134056, l='MpServer', x=344.50, y=57.00, z=239.50], EntityZombie['Zombi'/127914, l='MpServer', x=218.74, y=53.00, z=228.52], EntityCreeper['Creeper'/134313, l='MpServer', x=234.50, y=43.00, z=89.50], EntitySquid['Calamar'/134062, l='MpServer', x=238.22, y=59.89, z=157.71], EntitySquid['Calamar'/134063, l='MpServer', x=235.94, y=59.38, z=157.99], EntitySquid['Calamar'/134060, l='MpServer', x=293.40, y=62.55, z=153.71], EntitySquid['Calamar'/134061, l='MpServer', x=280.36, y=57.00, z=139.27], EntitySquid['Calamar'/134064, l='MpServer', x=239.36, y=57.98, z=162.72], EntitySquid['Calamar'/134065, l='MpServer', x=230.49, y=61.94, z=165.56], EntityItem['item.item.egg'/125367, l='MpServer', x=262.29, y=63.00, z=126.74], EntitySentry['Torreta'/121785, l='MpServer', x=403.59, y=96.00, z=154.10], EntityCreeper['Creeper'/127929, l='MpServer', x=276.23, y=53.00, z=182.49], EntitySentry['Torreta'/121787, l='MpServer', x=403.59, y=96.00, z=154.10], EntitySkeleton['Esqueleto'/125626, l='MpServer', x=290.18, y=44.00, z=163.58], EntitySentry['Torreta'/121786, l='MpServer', x=403.59, y=96.00, z=154.10], EntityZombie['Zombi'/133561, l='MpServer', x=271.50, y=23.00, z=232.50], EntitySentry['Torreta'/121789, l='MpServer', x=403.59, y=96.00, z=154.10], EntitySentry['Torreta'/121788, l='MpServer', x=403.59, y=96.00, z=154.10], EntitySentry['Torreta'/121791, l='MpServer', x=403.59, y=96.00, z=154.10], EntitySentry['Torreta'/121790, l='MpServer', x=403.59, y=96.00, z=154.10], EntitySentry['Torreta'/121793, l='MpServer', x=403.59, y=96.00, z=154.10], EntitySentry['Torreta'/121792, l='MpServer', x=403.59, y=96.00, z=154.10], EntitySentry['Torreta'/121795, l='MpServer', x=403.59, y=96.00, z=154.10], EntitySentry['Torreta'/121794, l='MpServer', x=403.59, y=96.00, z=154.10], EntitySentry['Torreta'/117956, l='MpServer', x=219.50, y=83.00, z=243.50], EntitySentry['Torreta'/117446, l='MpServer', x=226.50, y=87.00, z=241.50], EntityCreeper['Creeper'/134344, l='MpServer', x=260.50, y=39.00, z=158.50], EntityItem['item.item.rottenFlesh'/133069, l='MpServer', x=293.10, y=69.00, z=172.23], EntityCreeper['Creeper'/133840, l='MpServer', x=229.50, y=49.00, z=221.50], EntityCreeper['Creeper'/133841, l='MpServer', x=226.03, y=50.00, z=227.70], EntitySentry['Torreta'/46551, l='MpServer', x=293.50, y=97.00, z=197.50], EntityCreeper['Creeper'/134362, l='MpServer', x=281.50, y=20.00, z=178.50], EntityCreeper['Creeper'/134372, l='MpServer', x=332.50, y=33.00, z=138.50], EntityCreeper['Creeper'/134373, l='MpServer', x=333.50, y=33.00, z=136.83], EntityItem['item.item.egg'/126185, l='MpServer', x=264.07, y=63.00, z=141.11], EntitySentry['Torreta'/46315, l='MpServer', x=319.50, y=97.00, z=225.50], EntityEnderman['Enderman'/134377, l='MpServer', x=322.50, y=23.00, z=157.50], EntityBat['Murciélago'/133359, l='MpServer', x=239.42, y=49.81, z=193.02], EntitySkeleton['Esqueleto'/134125, l='MpServer', x=337.73, y=16.00, z=85.50], EntitySentry['Torreta'/66037, l='MpServer', x=300.50, y=100.00, z=226.50], EntityZombie['Zombi'/133110, l='MpServer', x=285.50, y=18.00, z=225.50], EntityCreeper['Creeper'/134134, l='MpServer', x=273.50, y=19.00, z=155.50], EntityCreeper['Creeper'/129275, l='MpServer', x=224.79, y=64.00, z=197.49], EntitySkeleton['Esqueleto'/127226, l='MpServer', x=235.29, y=59.00, z=187.54], EntitySkeleton['Esqueleto'/133881, l='MpServer', x=341.50, y=13.00, z=85.50], EntityBat['Murciélago'/134396, l='MpServer', x=283.53, y=18.11, z=177.53]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:532)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2741)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:419)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 741927128 bytes (707 MB) / 2147483648 bytes (2048 MB) up to 2147483648 bytes (2048 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2847 Optifine OptiFine_1.12.2_HD_U_F5 15 mods loaded, 15 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State  | ID               | Version                     | Source                                   | Signature |
	|:------ |:---------------- |:--------------------------- |:---------------------------------------- |:--------- |
	| LCHIJA | minecraft        | 1.12.2                      | minecraft.jar                            | None      |
	| LCHIJA | mcp              | 9.42                        | minecraft.jar                            | None      |
	| LCHIJA | FML              | 8.0.99.99                   | forge-1.12.2-14.23.5.2847.jar            | None      |
	| LCHIJA | forge            | 14.23.5.2847                | forge-1.12.2-14.23.5.2847.jar            | None      |
	| LCHIJA | securitycraft    | v1.8.17                     | [1.12.2]+SecurityCraft+v1.8.17.jar       | None      |
	| LCHIJA | backpack         | 3.0.2                       | backpack-3.0.2-1.12.2.jar                | None      |
	| LCHIJA | modcurrency      | 1.12.0-2.0.0-ALPHA-20200120 | Currency-1.12.0-2.0.0-ALPHA-20200120.jar | None      |
	| LCHIJA | ptrmodellib      | 1.0.4                       | PTRLib-1.0.4.jar                         | None      |
	| LCHIJA | props            | 2.6.3                       | Decocraft-2.6.3_1.12.2.jar               | None      |
	| LCHIJA | elevatorid       | 1.3.14                      | ElevatorMod-1.12.2-1.3.14.jar            | None      |
	| LCHIJA | cfm              | 6.3.1                       | furniture-6.3.1-1.12.2.jar               | None      |
	| LCHIJA | jei              | 4.15.0.268                  | jei_1.12.2-4.15.0.268.jar                | None      |
	| LCHIJA | moreplayermodels | 1.12.2                      | MorePlayerModels_1.12.2-(05Dec19).jar    | None      |
	| LCHIJA | rustic           | 1.1.2                       | rustic-1.1.2.jar                         | None      |
	| LCHIJA | xray             | 2.0.0                       | xray-1.12.2-1.6.0.jar                    | None      |

	Loaded coremods (and transformers): 
	GL info: ' Vendor: 'Intel' Version: '4.6.0 - Build 26.20.100.7529' Renderer: 'Intel(R) UHD Graphics 620'
	Launched Version: 1.12.2-forge1.12.2-14.23.5.2847
	LWJGL: 2.9.4
	OpenGL: Intel(R) UHD Graphics 620 GL version 4.6.0 - Build 26.20.100.7529, Intel
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: No
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: Español (España)
	Profiler Position: N/A (disabled)
	CPU: 8x Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz
	OptiFine Version: OptiFine_1.12.2_HD_U_F5
	OptiFine Build: 20191204-141934
	Render Distance Chunks: 4
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.6.0 - Build 26.20.100.7529
	OpenGlRenderer: Intel(R) UHD Graphics 620
	OpenGlVendor: Intel
	CpuCount: 8

**Comment by Beardlessbrady** [comment]
I need information. What version of the mod? What version of forge? Are there any other mods? Does it still occur with no other mods present? Can you isolate which mod is causing the issue?

**Comment by Kozmito** [comment]
The version of the mod is Currency-1.12.0-2.0.0-ALPHA-20200120. The version of forge is 14.23.5.2847. Yes, there are more mods. The mod who is causing the issue? I think that it´s the Currency because when I get near the vending machine it bugs and then it crashes.

**Comment by Beardlessbrady** [comment]
Does it still occur when you run JUST currency?

**Comment by Kozmito** [comment]
I have only the bug in servers. I already tested it.

**Comment by Kozmito** [comment]
It has the same crash with and without mods.

**Comment by Kozmito** [comment]
Also, the screen gets black before crashing.

**Comment by Kozmito** [comment]
Oh, the problem was the ladders who caused the vending machine to cause the crash. I think I solved it.
Thanks.
