### ISSUE TITLE
 Pay with your wallet, give items for free?

### ISSUE THREAD

**Issue by NoBi-ThE-SoLo-MaStEr** [BeardlessBrady/Currency-Mod#107]
I rarely encountered this problem, but a significant problem for the business when some items are suddenly given away. (At least for the seller)
Unfortunately, I can only provide these pictures and a list of mods that I use.
Maybe another mod is not cooperating or the Forge version is not working properly with this mod?
My Forge Mod Version is: 1.12.2-Forge1.12.2-14.23.5.2847.
A total of 162 mods are loaded, which certainly does not make things easier.
In the following pictures, the machine was created creatively. And with the attitude for infinite objects. (Maybe this information is relevant?)

![2020-03-17_02 43 21 - Kopie](https://user-images.githubusercontent.com/62295449/76867950-86752b00-6866-11ea-8b27-cc94d35a9c4e.png)
![2020-03-17_02 43 28 - Kopie](https://user-images.githubusercontent.com/62295449/76867954-87a65800-6866-11ea-8a02-d394fa5ca03d.png)
![2020-03-17_02 43 33 - Kopie](https://user-images.githubusercontent.com/62295449/76867958-883eee80-6866-11ea-97f3-21b5e7a55996.png)
![2020-03-17_02 43 43 - Kopie](https://user-images.githubusercontent.com/62295449/76867960-88d78500-6866-11ea-90aa-558641c88626.png)
![2020-03-17_02 43 55 - Kopie](https://user-images.githubusercontent.com/62295449/76867964-89701b80-6866-11ea-82b7-8ae447ac43f2.png)
![2020-03-17_02 43 59 - Kopie](https://user-images.githubusercontent.com/62295449/76867965-8a08b200-6866-11ea-97e3-caa85b12262f.png)
![2020-03-17_02 44 04 - Kopie](https://user-images.githubusercontent.com/62295449/76867970-8aa14880-6866-11ea-94ea-640a9845ad02.png)
![2020-03-17_02 44 16 - Kopie](https://user-images.githubusercontent.com/62295449/76867973-8b39df00-6866-11ea-8bd4-e0f1b8118836.png)
![2020-03-17_02 44 20 - Kopie](https://user-images.githubusercontent.com/62295449/76867975-8bd27580-6866-11ea-8d52-fbf9bc43290b.png)
![2020-03-17_02 44 26 - Kopie](https://user-images.githubusercontent.com/62295449/76867976-8c6b0c00-6866-11ea-9b7c-1aeba554e965.png)
![2020-03-17_02 44 51 - Kopie](https://user-images.githubusercontent.com/62295449/76867980-8d03a280-6866-11ea-98f1-2f83038b0012.png)
![2020-03-17_02 45 14 - Kopie](https://user-images.githubusercontent.com/62295449/76867983-8e34cf80-6866-11ea-80d6-89e34e94bede.png)
![2020-03-17_02 45 25 - Kopie](https://user-images.githubusercontent.com/62295449/76867985-8ecd6600-6866-11ea-8f20-3f9931f8c18d.png)
![2020-03-17_02 45 32 - Kopie](https://user-images.githubusercontent.com/62295449/76867986-8f65fc80-6866-11ea-8e6f-9ae97a2bb8c2.png)
![ModList_001](https://user-images.githubusercontent.com/62295449/76867990-8ffe9300-6866-11ea-8502-0068967592cb.png)
![ModList_002](https://user-images.githubusercontent.com/62295449/76867991-90972980-6866-11ea-9176-0f882a555404.png)
![ModList_003](https://user-images.githubusercontent.com/62295449/76867993-90972980-6866-11ea-8b2e-21f0db50f0f2.png)
![ModList_004](https://user-images.githubusercontent.com/62295449/76867994-912fc000-6866-11ea-85f3-4230fe5fe57f.png)
![ModList_005](https://user-images.githubusercontent.com/62295449/76867996-912fc000-6866-11ea-81f7-b4cc9ab7a3cf.png)

**Comment by Tanguygab** [comment]
Hey, the 1.0 from the mod isn't in developement anymore, BeardlessBrady is woking on 2.0 who's a rewrite. And for your issue, you had your wallet into the money input slot x) you can see its money getting drained each time you buy an item

**Comment by NoBi-ThE-SoLo-MaStEr** [comment]
> Hey, the 1.0 from the mod isn't in developement anymore, BeardlessBrady is woking on 2.0 who's a rewrite. And for your issue, you had your wallet into the money input slot x) you can see its money getting drained each time you buy an item

For me, however, it doesn't look like money is being withdrawn every time. O.o

**Comment by Beardlessbrady** [comment]
Closing due to no longer supporting 1.0. Use 2.0 Alpha
