### ISSUE TITLE
BetterQuesting Error?

### ISSUE THREAD

**Issue by philipp-s06** [BeardlessBrady/Currency-Mod#108]
Hello, BetterQuesting is only show the "DO NOT USE ME, REPLACED BY ONE DOLLAR COIN" item. I will use this for a "REWARD" in the questbook. How can i use the dollar bills?
![bq](https://user-images.githubusercontent.com/61699413/78500895-72cc2e80-7759-11ea-8c14-30f85b290e27.png)

**Comment by Beardlessbrady** [comment]
The other currencies are that item with different metadata. Can you change the metadata in that mod?

**Comment by philipp-s06** [comment]
Yes i can. Have i to change the NBT Tag?

**Comment by philipp-s06** [comment]
Here is the Link to curseforge: https://www.curseforge.com/minecraft/mc-mods/better-questing
Here is the Link to GitHubWiki: https://github.com/Funwayguy/BetterQuesting/wiki

**Comment by Beardlessbrady** [comment]
Then all you need to do is change the metadata, 0 is the "DO NOT USE"
