### ISSUE TITLE
Negative money when adding money

### ISSUE THREAD

**Issue by idnthvn** [BeardlessBrady/Currency-Mod#110]
Love the mod, However does not comply with our server

Minecraft 1.12.2
SpongeForge RC4007
Forge 2847

So in singleplayer, the vending machine works as it should.
While in server it does not.
Server has the added Mods that Singleplayer does not.
SpongeForge
TiQuality

Now what is the issue:
Place down Vending machine. Take the $100.00 currency and add 4 to the machine.
Machine SHOULD read $400.00. (Again in Singleplayer, this is correct) in Server, the value reads -255.36.

Now, the vending machine still functions but is buggy. If there is an item in the machine that is under the $400.00, the vending machine states there are no funds since it reads -255. BUT if you exit the machine, it places one into your inventory.  Also, it you put 400 into the machine, and it reads -255 and hit thecash out button, it does still give you back 400.

Again i am thinking this is going to be a SpongeForge issue

Edit: Removed SpongeForge and Ti-Quality and still acts up on server

Tested on a completely blank server & client
Forge 2847
minecraft 1.12.2
JEI
and Currency Mod 2.0 Beta 
That is all i have installed and this issue is still there

**Comment by Tanguygab** [comment]
I didn't really understand how does this bug happen, could you maybe send some screenshots ?

**Comment by idnthvn** [comment]
Showing that i set up a Granite block for $500.00
![2020-04-18_07 32 42](https://user-images.githubusercontent.com/6686550/79636625-27e1ec00-8147-11ea-88df-f14b1e8894ce.png)
Have 8 $100.00 Bills
![2020-04-18_07 32 57](https://user-images.githubusercontent.com/6686550/79636630-30d2bd80-8147-11ea-9392-0e0b548ece73.png)
Adding Money $100.00
![2020-04-18_07 33 03](https://user-images.githubusercontent.com/6686550/79636635-3af4bc00-8147-11ea-8ce9-82b9af617b88.png)
$200.00
![2020-04-18_07 33 05](https://user-images.githubusercontent.com/6686550/79636638-421bca00-8147-11ea-86fa-33c95cce5a62.png)
$300.00
![2020-04-18_07 33 07](https://user-images.githubusercontent.com/6686550/79636641-46e07e00-8147-11ea-8e4c-d2de54671076.png)
$400.00
![2020-04-18_07 33 08](https://user-images.githubusercontent.com/6686550/79636642-4ba53200-8147-11ea-9697-8e409fdb3906.png)
$500.00
![2020-04-18_07 33 10](https://user-images.githubusercontent.com/6686550/79636645-519b1300-8147-11ea-81f1-c3cdb1300599.png)
$600.00
![2020-04-18_07 33 11](https://user-images.githubusercontent.com/6686550/79636649-565fc700-8147-11ea-8a4c-16acbce87aee.png)
$700.00
![2020-04-18_07 33 13](https://user-images.githubusercontent.com/6686550/79636659-5f509880-8147-11ea-9747-f3cd1a686ae2.png)
$800.00
![2020-04-18_07 33 14](https://user-images.githubusercontent.com/6686550/79636665-64ade300-8147-11ea-9944-6ba5f025d3b7.png)
Clicked on Granite Block (as you can see it says Not Enough Funds
Money went to $300.00
Did not recieve block while in this screen
![2020-04-18_07 33 30](https://user-images.githubusercontent.com/6686550/79636682-7e4f2a80-8147-11ea-8581-ea32509656c4.png)
However, when you back out of the machine, you receive the item.
![2020-04-18_07 33 34](https://user-images.githubusercontent.com/6686550/79636695-8d35dd00-8147-11ea-9ea3-367528452428.png)

Also, when i have $800.00 and i click the return money button, this is what shows.
![2020-04-18_07 33 52](https://user-images.githubusercontent.com/6686550/79636707-a3dc3400-8147-11ea-864f-6d86f2fa78af.png)
But when you click on the coins to move them, it returns back to the 8 $100.00 Bills
![2020-04-18_07 34 01](https://user-images.githubusercontent.com/6686550/79636713-b0608c80-8147-11ea-9fdd-42ac309392e5.png)


The following is installed:
Minecraft 1.12.2
Forge 1.12.2 - version 2847
JEI 1.12.2-4.15.0.293 - SO i can access your mod items as they do not show up in creative tab
Currency-1.12.0-2.0.0-Alpha-20200315


Hope this helps :)

**Comment by Tanguygab** [comment]
Yup, there may be a "little" problem x) thanks for reporting, Brady will look into it when he have time
(Btw, can you rename the name to something like "Negative money bug in Vending Machine" since it isn't related to sponge ? thanks)

**Comment by idnthvn** [comment]
Done, 
I thought i renamed it   when i last edited the initial comment, must not of.  But ya, not in a major rush.  we are playing/messing around with the older version at the moment while we working on stuff

**Comment by Beardlessbrady** [comment]
Are you able to reproduce this issue when it's just the currency mod installed ?

**Comment by idnthvn** [comment]
So i now see you have an actual Tab button on the second page (i was trying to search for the blocks)
Now in single player, it works fantastic. as expected. This only occurs on server.
Both Server and Client have
Minecraft 1.12.2
Forge 1.12.2 - version 2847
Currency-1.12.0-2.0.0-Alpha-20200315

This is all that is added
edit: I even tested on a clean install, deleted everything other than mods, and let everything else create new. Still same (singleplayer works/ Server did not)

**Comment by Beardlessbrady** [comment]
Thats why I didn't catch it, I always forget to test on server before I release...I will try to squash this bug tomorrow! Thanks for reporting it!!

**Comment by idnthvn** [comment]
Excited for the fix :)

**Comment by Beardlessbrady** [comment]
I fixed it, was a really stupid mistake on my end (whoopsie). This maaay break a few other money related things so I'd appreciate if you tested as much as you can of the mod just encase I broke something. Thanks for reporting :)

**Comment by Beardlessbrady** [comment]
Releasing incoming with fix

**Comment by idnthvn** [comment]
Seems to be working now correctly.
I see now there is no longer a wallet?
i have now a "item.playercurrency.name" that is a coin look with NO printed on it and a
"tile.modcurrency:blockcurrencydesigner.name" with the black/purple texture on it.
do not know if they are all intentional, and the disappearing of the wallet?

**Comment by Beardlessbrady** [comment]
The wallet is only in 1.0 of the mod, it will be coming to 2.0

As for the unfinished blocks and items in the 2.0 ALPHA. It is an alpha thus it will have unfinished stuff, ignore them for now
