### ISSUE TITLE
Rendering Issue

### ISSUE THREAD

**Issue by idnthvn** [BeardlessBrady/Currency-Mod#112]
Currency 1.12-2.0.0-ALPHA 20200419

After fix, I am attending to this error now (i do have other mods and Optifine installed.
It appears to be the vending machine.

[crash-2020-04-20_07.34.14-client.txt](https://github.com/Beardlessbrady/Currency-Mod/files/4503147/crash-2020-04-20_07.34.14-client.txt)

**Comment by Beardlessbrady** [comment]
That should be an easy fix. Could you join the discord group so I can have you test a build as I probably wont be able to reproduce your issue.
