### ISSUE TITLE
Trade-In Machine (Critical) - ALPHA 2.0

### ISSUE THREAD

**Issue by SlendyMcTendies** [BeardlessBrady/Currency-Mod#113]
The Trade-In Machine has 4 Major Bugs

1) Non-Owners can access the stock/inventory of the machine and effectively steal any money placed within the machine by clicking the "Trade" button while exchanging items for money.

2) When "Until" is set to 0 (or what would be assumed as "no limit"), sold items simply disappear from the machine.

3) Reclaiming money in a Trade-In machine does not properly update the GUI and continues allowing trades, but does not give any money. 

4) In addition to 3, this state causes users who access the machine to spawn the "bulk" amount of items designated by the machine, regardless of if those items exist in the player's inventory.

--------------------------------------------------------------------------------------------------------------

I have 2 custom currencies set to $500 and $1000 in the config and gave them their own textures and models with a resource pack I created. I don't have a reason to believe the custom currencies are causing any of these issues, but I figured I'd at least mention it.

**Comment by SlendyMcTendies** [comment]
Vending Machine GUI doesn't update either.

**Comment by Beardlessbrady** [comment]
I think I have fixed issue 3 and 4. If you can join the community discord I can give you the build to test your issues with.

**Comment by Beardlessbrady** [comment]
I know this is a very late responce. I am finally back on working on the mod again.

1. How did I miss that! Fix coming in latest build.
2. I can't quite reproduce this one, can you give me more info?
3. This one I can't reproduce either.
4. Not Understanding this one either
