### ISSUE TITLE
Creative Trade-In Machine doesn't have infinite funds

### ISSUE THREAD

**Issue by brisingraerowing** [BeardlessBrady/Currency-Mod#115]
As per title. v2.0-alpha-20200420

**Comment by Beardlessbrady** [comment]
I haven't added the functionality for the creative trade in machine yet. Coming verySOON!

**Comment by wanou067** [comment]
Hello, when do you think this functionnality will release ?

**Comment by Gunnbra** [comment]
2.0 was scrapped due to a huge desync bug. It is no longer being worked on
