### ISSUE TITLE
Adding items to existing stacks in machines voids the items in the machine.

### ISSUE THREAD

**Issue by brisingraerowing** [BeardlessBrady/Currency-Mod#118]
If you have a stack of items in a machine, and try to drop more on the stack, the stack in the machine gets voided. Also, if you try shift-clicking the items into the machine, the first click will pull the items in the machine into the stack you clicked on, which breaks the bundle if the item is part of one.

**Comment by Beardlessbrady** [comment]
I can't reproduce this issue. Can you give more details/ show screenshots? Is it on server with other mods and can you reproduce it alone?
