### ISSUE TITLE
Feature Request - Cash Drops from mobs

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [BeardlessBrady/Currency-Mod#12]
I would to kill mobs GTA style and steal their cash or actually turn XP into cash ;)

**Comment by Beardlessbrady** [comment]
I already have features similar to this on my todo list:
-Rare Mob drop (Money Bag)
-XP to Money type Machine

**Comment by P3rf3ctXZer0** [comment]
Your awesome :)

**Comment by Beardlessbrady** [comment]
haha thanks. There wont be any new features next update, it will mainly just be polish. After that I will start on all the many features I have planned. I suppose I could list those somewhere on the github

**Comment by Beardlessbrady** [comment]
https://github.com/BeardlessBrady/Currency-Mod/blob/master/Todo%20List
