### ISSUE TITLE
Piping into vending machine voids items

### ISSUE THREAD

**Issue by ashbob16478** [BeardlessBrady/Currency-Mod#128]
Im trying to automate importing of items into vending machines (i dont want the items to be infinite) however when i try to import into them using any form of piping or even vanilla hoppers the item vanishes.

Im using version: Currency-1.12.0-1.3.11 and its on a server

**Comment by ashbob16478** [comment]
Still not managed to figure out why this is happening? Is it intended that you can push items into vending machines or is it a bug or am i just missing something?

**Comment by ashbob16478** [comment]
Gonna bump it again in hopes of getting some kind of response...

**Comment by Gunnbra** [comment]
Sorry I've been very busy with work. I'll look into it when I can

**Comment by ashbob16478** [comment]
Alright no worries, take your time mate. Just wanted to ensure it was seen tbh
