### ISSUE TITLE
Will there be an update?

### ISSUE THREAD

**Issue by Scwestbrook** [BeardlessBrady/Currency-Mod#129]
Is this mod going to be updated? I'd hate to see another mod go to lack of development.

**Comment by Beardlessbrady** [comment]
My life has been very busy the past few years. I have been in University and now I am juggling a software development job on top of that. 

Not only that but my priorities have changed. I used to work on this mod on my free time, now my free time goes to being with my family. 

I would love to continue development but I just simply don't have the time right now.

**Comment by Scwestbrook** [comment]
OK, also, how do I download the 1.16 update off curseforge? It looks complete, but I can't find it.

**Comment by Scwestbrook** [comment]
As in, it looks like you made a 1.16.3 update, but how do I download?

**Comment by Beardlessbrady** [comment]
I did not even touch 1.16.3

**Comment by Scwestbrook** [comment]
That's odd, there's a 1.16 version linked in the Github, but it takes me to
the files section.

**Comment by Beardlessbrady** [comment]
I think that's just a direct port of 1.12. I didn't do anything to it to actually fix any issues so it doesn't run

**Comment by Scwestbrook** [comment]
OK.
