### ISSUE TITLE
Crash Minecraft Client in Trade Client/Vending MC 1.12.2 

### ISSUE THREAD

**Issue by Everlast14** [BeardlessBrady/Currency-Mod#130]
In the Trade Machine or the Vending Machine, when you are going to place the amount of the item in question, if you place instead of 5.00, you enter 5:00, it crashes the entire client.

The Crash happens exactly when instead of putting the point (5.00), you place two points (5:00). Maybe it happens with any other symbol, I don't know.

Besides, can you add an ATM?

Thanks, nice mod!

**Comment by Gunnbra** [comment]
Hi. Unfortunately the mod is in LIMBO due to real life being very busy. I have no time and no idea when I will be able to work on the mod again.

**Comment by Beardlessbrady** [comment]
Hi. Unfortunately the mod is in LIMBO due to real life being very busy. I have no time and no idea when I will be able to work on the mod again.
