### ISSUE TITLE
Wallets Pop Out Of Machines

### ISSUE THREAD

**Issue by AgentCPU0** [BeardlessBrady/Currency-Mod#131]
When you place a wallet into a vending machine and exit the machine, it pops out of the machine instead of popping back into your inventory. This is counterintuitive for 2 reasons: 1, every other Minecraft block with a GUI, vanilla or modded, will pop the items back into your inventory if it doesn't store the items, and 2, if you're not paying attention, you'll forget about your wallet and it will eventually despawn, which can cause you to lose tons of hard earned cash

**Comment by Gunnbra** [comment]
Hi. Unfortunately the mod is in LIMBO due to real life being very busy. I have no time and no idea when I will be able to work on the mod again.

**Comment by Beardlessbrady** [comment]
Hi. Unfortunately the mod is in LIMBO due to real life being very busy. I have no time and no idea when I will be able to work on the mod again.
