### ISSUE TITLE
1.12: Problems with the trading / vending machine

### ISSUE THREAD

**Issue by Mokalyn** [BeardlessBrady/Currency-Mod#132]
Description:

On a LAN map with my friend (Survival Map - We build in creative). I have placed a store with 1 exchange machine and 4 vending machines.

In the exchange machine that I have placed I place the items that I am looking for and the value in which I will buy them, however ...

1- If my friend clicks on TRADE (on my machine), he can place his items and even get my money.

2- The Machine does not update the UI information in real time. If I place a new item, he can't see it, he must restart de game. If I change the price, he cannot see it, he must restart again.

In the vending machine it is more noticeable that it does not update in real time. The Stock of items does not change.

Ejm: If I put 64 stacks of X thing, he buys one, it should be 63. For him if it is updated, but I still see 64.

If I place a new item, he can't see it, he must restart.

---

The second problem is that if by mistake you put in the price of the item that you are going to place .. (Ahem)

$ 5:00, instead of $ 5.00, the MC crashes completely.

---
The third problem, the exchange machine in the Profit UI, it keeps increasing and increasing after each transaction, there is no way to return to 0?

And the UI of Money (the amount that the machine has to pay), the following happens:

I put $ 100 in, $ 100 appears in the UI. I take out the $ 100, the UI still reflects the $ 100. I put $ 100 back in, now it reflects $ 200. Why?

---

This is all a two-person LAN map (Survival). With normal machines, not Creative. We have verified that the information is not updated, apart from other people can access your machine, withdraw money or use it to put their items. the version is 1.12.2. 

BTW, GOOD MOD! Anyway to have a option to Monster drop money (coins) and ATM? 

Greetings!

**Comment by Beardlessbrady** [comment]
1.12 is no longer supported. Sorry
