### ISSUE TITLE
Information Requested - 1.10.2 

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [BeardlessBrady/Currency-Mod#14]
I need a wiki explaining usage. I need to know how to setup a sell infinite machine for map makers. I need to know if we have a RECYCLER machine that recycles any item for a set price. Recycler should only work with mods unless players want to sell things for a dollar at a time.

**Comment by Beardlessbrady** [comment]
The mod is in beta. There are abit of explanation on how the mod works on the curse page, its outdated but will be fixed on release. I will not be adding a recycler
