### ISSUE TITLE
[Bug] ATM Not Appearing What So Ever

### ISSUE THREAD

**Issue by Charlie-Gallie** [BeardlessBrady/Currency-Mod#142]
**Issue:** The ATM block doesn't appear to exist in the game what so ever, not even as a textureless item. It's missing from the creative menu, the "Currency for Blockheads" book, Just Enough Items menu, and there is no reference to it when tabbing `/give PLAYER modcurrency:`
**Mod Versions Tested**: _1.12-1.3.11_, _1.12-1.3.9_
**Forge Versions Tested:** _14.23.5.2847_, _14.23.5.2854_, _14.23.5.2855_ (All 1.12.2)
**Screen Shots:** 
![image](https://user-images.githubusercontent.com/73857381/134195079-932f5cfe-42f2-4aca-8728-cceb0d7fe535.png)
![image](https://user-images.githubusercontent.com/73857381/134195153-2bf89e19-2369-471e-a199-17c722efeb05.png)
![image](https://user-images.githubusercontent.com/73857381/134195339-d0565a72-98d5-40de-9d3c-503a5f26c467.png)
![image](https://user-images.githubusercontent.com/73857381/134195435-1c5df886-d83c-41a6-a3b2-48b68fcd8621.png)
**The textureless item in the JEI menu is an upgrade item (`modcurrency:upgrade`, `item.modcurrency:upgrage_0.name`)**

**Further Notes:** Pressing where the ATM should exist in the "Currency for Blockheads" book shows a blank page as demonstrated below:
![image](https://user-images.githubusercontent.com/73857381/134195865-85c741a5-c9b8-4956-9564-510c26adb5be.png)

**Should you need me to test anything else to help debug this, feel free to let me know.**

**Comment by Tanguygab** [comment]
the ATM got removed in the last versions of GOC v1, and will be back at some point in v2 (you can keep track of the development on [Discord](https://discord.gg/Uw8tBCk) and on [Trello](https://trello.com/b/V7aAaXo8/good-ol-currency))

**Comment by Charlie-Gallie** [comment]
> the ATM got removed in the last versions of GOC v1, and will be back at some point in v2 (you can keep track of the development on [Discord](https://discord.gg/Uw8tBCk) and on [Trello](https://trello.com/b/V7aAaXo8/good-ol-currency))

I apologise, I didn't realise. Thank you for letting me know.
