### ISSUE TITLE
Issue - Exchange Machine; Not working!

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [BeardlessBrady/Currency-Mod#15]
I can't get the exchange machine to work period.

**Comment by P3rf3ctXZer0** [comment]
![2016-12-30_22 46 19](https://cloud.githubusercontent.com/assets/10351221/21575858/ce88c644-cee1-11e6-9366-5cb58efe93f7.png)
![2016-12-30_22 47 07](https://cloud.githubusercontent.com/assets/10351221/21575860/ebbbc054-cee1-11e6-9463-1d97efa89f7a.png)

I can sell stuff but pushing the cash button gives me nothing!
![2016-12-30_22 44 27](https://cloud.githubusercontent.com/assets/10351221/21575852/a517b0ae-cee1-11e6-84ce-98b208cc716e.png)

**Comment by Beardlessbrady** [comment]
You set the exchange machine to infinite, there fore well in the EDIT MODE the cash button wont do anything because...its infinite

**Comment by P3rf3ctXZer0** [comment]
How do I make a basic way for players to just sell items?

**Comment by Beardlessbrady** [comment]
The cash button should work on the mode without the tabs, let me double check

**Comment by Beardlessbrady** [comment]
Yes it does work. So if a player sells something to the exchange machine then clicks the 'cash' button the money should pop out somewhere. I know its a bit crazy how it spawns sometimes, fixed in next build which should come out in a week or two

**Comment by Beardlessbrady** [comment]
Understand?

**Comment by P3rf3ctXZer0** [comment]
Yeah.

**Comment by Beardlessbrady** [comment]
Your welcome, if you have any other issues let me know
