### ISSUE TITLE
Major Issue - Crash - 1.10.2 Forge 221 - Serverside Crash

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [BeardlessBrady/Currency-Mod#17]
https://gist.github.com/P3rf3ctXZer0/135ff819abfde143eafa4b1acd0851c3

Please help!

**Comment by Beardlessbrady** [comment]
Looking into it. For the record please don't post issues on the comments on the curse forge page please

**Comment by P3rf3ctXZer0** [comment]
I just didn't want to miss you ... I do apologize.

**Comment by Beardlessbrady** [comment]
It's alright. I get emails whenever someone reports a bug so I am notified right away. Bug has been fixed, uploading Version 1.4.1 now

**Comment by Beardlessbrady** [comment]
Question, do you have a skype or something I could contact you with. That way you could help me test releases before they are released, if you are interested :)

**Comment by P3rf3ctXZer0** [comment]
Yes; do you mind discord to ts3?

**Comment by Beardlessbrady** [comment]
I have both, up to you

**Comment by P3rf3ctXZer0** [comment]
https://discord.gg/vgf42GV

**Comment by P3rf3ctXZer0** [comment]
I am mostly on Teamspeak 3 and Discord 158.69.57.19:9024
