### ISSUE TITLE
 1.11.2-1.0.0-Beta crashes dedicated Forge 1.11.2 build 2230 on startup

### ISSUE THREAD

**Issue by kreezxil** [BeardlessBrady/Currency-Mod#18]
Notes:
     looking for client side classes

crash report:
https://gist.github.com/aa7138059e8c0af385191af68d8e7fa7

fml server latest:
https://gist.github.com/57c3494eeb23d3e0800098336b2a3f83

**Comment by Beardlessbrady** [comment]
Fix Inbound on 1.11.2-1.0.1-Beta
