### ISSUE TITLE
Clientside crash with Exchange Machine

### ISSUE THREAD

**Issue by brisingraerowing** [BeardlessBrady/Currency-Mod#19]
When I viewed the item edit tab in the Exchange machine, the item quantity value was some unicode characters, and I got the following crash when clicking the tab again to close it:

[Crash Log](https://gist.github.com/BrisingrAerowing/b0acb612702b3489e6db881e56184ca0)

There seems to be some kind of encoding error here (or not, I don't know much about Java)

EDIT: [Modlist](http://www.modlister.com/user/BrisingrAerowing)

**Comment by Beardlessbrady** [comment]
Alright so I can reproduce it. Seems to be an issue with the new packet system I implemented.

**Comment by Beardlessbrady** [comment]
Thank you for reporting the issue, it is very much appreciated! New version coming in the next hour
