### ISSUE TITLE
[Feature Request] Allow selling stacks of items

### ISSUE THREAD

**Issue by brisingraerowing** [BeardlessBrady/Currency-Mod#20]
Currently the Vending Machine sells one item at a time. I would like to be able to sell, say, 64 Redstone Dust for $5, which isn't currently possible. Could this be added?

A possible way to do it would be to have a bag that can hold up to one stack of items and will give the items when it is used. I looked for a mod that has something like that, but didn't find anything.

**Comment by Beardlessbrady** [comment]
Hmm I could look into something like that actually. Won't be added right away however, but I will add it to my todo list. If I can't think of a plausible solution Ill write on this issue on a later date

**Comment by Beardlessbrady** [comment]
This could create an unbalance to vanilla mechanics however. Allowing the player to carry multiple stacks of an item in one slot. Any idea on how to fix this issue?

**Comment by brisingraerowing** [comment]
The bags won't stack at all.

**Comment by Beardlessbrady** [comment]
sounds good, Ill let you know how it goes

**Comment by Beardlessbrady** [comment]
I could just add a textfield to the settings tab so the owner can set how many of that item is sold for said price?

**Comment by Beardlessbrady** [comment]
Yes I think I'll just do the latter. The bags would be fun but it will make things too over complicated for the player

**Comment by brisingraerowing** [comment]
Sounds good to me.
