### ISSUE TITLE
client crash when click buffer slots of a  vending machine

### ISSUE THREAD

**Issue by OLOrz996** [BeardlessBrady/Currency-Mod#21]
[crash-2017-04-01_17.02.38-client.txt](https://github.com/BeardlessBrady/Currency-Mod/files/887495/crash-2017-04-01_17.02.38-client.txt)

**Comment by Beardlessbrady** [comment]
What version of the mod are you using? What exactly did you do before the crash occurred? Can you recreate it?

**Comment by OLOrz996** [comment]
mod version:Currency-1.10.2-1.0.2.jar
forge version:forge-1.10.2-12.18.3.2254

I can recreate it. I place a vending machine and change into the stock mode. Then I just click the buffer slots and it crash. Every time I click the buffer slots it crash immediately. And then I click the slot right of the Profit button. It crash again.

**Comment by Beardlessbrady** [comment]
Alright Ill look into it in a bit and get back to you

**Comment by OLOrz996** [comment]
I just find that sometimes it crash when I do something wrong. For example, I try to put currency into the right-top slot when the machine is in stock mode.

**Comment by Beardlessbrady** [comment]
I don't test everything before release because I'm a derp. thanks for posting an issue, fix coming out asap
