### ISSUE TITLE
game crashed when I was fooling around with the mod

### ISSUE THREAD

**Issue by PSILONCRAFT** [BeardlessBrady/Currency-Mod#23]
[crash-2017-05-01_22.38.26-client.txt](https://github.com/BeardlessBrady/Currency-Mod/files/968755/crash-2017-05-01_22.38.26-client.txt)

**Comment by Beardlessbrady** [comment]
Can I have more details.
Modpack: ?
MC Version:
Mod Version:
Can you recreate it again easily?
Single or Multiplayer?

**Comment by PSILONCRAFT** [comment]
just download the PROJECT PSILONCRAFTED from vurseforge there you will find all info you need
it is for 1.10.2

**Comment by Beardlessbrady** [comment]
That still doesn't answer all mt questions.
Did this error occur in single or multiplayer?
Were you able to recreate the issue again or was it a one time thing?

ALSO Can you tell me exactly what you were doing. Hard to fix the issue if I don't know what caused it as well as the above information

**Comment by PSILONCRAFT** [comment]
this is a multiplayer server
it happened while I was trying to replicate the wallet trick by having a stack of wallets and put money into the stack to duplicate the money

**Comment by PSILONCRAFT** [comment]
I will try one more time to replicate and answer you

**Comment by Beardlessbrady** [comment]
so you were trying to open a stack of wallets. I suppose that should be an easy fix

**Comment by Beardlessbrady** [comment]
I made the wallet no longer stack-able, I think this should fix the issues. Will be included in the next release coming soon
