### ISSUE TITLE
Feature: Sponge Support

### ISSUE THREAD

**Issue by nurdism** [BeardlessBrady/Currency-Mod#26]
A++ mod, loving it. It would be nice to have this mod work with [Sponge](https://spongepowered.org/), I was thinking just having a bridge for the [economy](https://docs.spongepowered.org/stable/en/plugin/economy/index.html) api, for the mods/plugins that need/use an economy.

**Comment by Beardlessbrady** [comment]
I suppose I can add it to my todo list but it won't be at the top

**Comment by nurdism** [comment]
Thanks for considering it 😄
