### ISSUE TITLE
Hardcrash when opening GUI

### ISSUE THREAD

**Issue by NielsPilgaard** [BeardlessBrady/Currency-Mod#27]
[crash-2017-06-10_21.22.22-client.txt](https://github.com/BeardlessBrady/Currency-Mod/files/1066076/crash-2017-06-10_21.22.22-client.txt)
[crash-2017-06-10_21.37.25-client.txt](https://github.com/BeardlessBrady/Currency-Mod/files/1066077/crash-2017-06-10_21.37.25-client.txt)

While placing Exchange Machines, I accidentally placed one on top of another, and opened it directly after - I crashed, with the crash log above. They should be nearly identical, as I got them while attempting to replicate that crash.

I hope there's enough info to remedy the issue (:

**Comment by Beardlessbrady** [comment]
One on top of another? As in you placed a one block exchanger ontop of another to create a double one? But opening it caused a crash?

**Comment by NielsPilgaard** [comment]
Yep - But it only caused a crash if the opening click was nearly simultaneous with placing the new block, so it's easily avoidable, just thought I'd mention it.

**Comment by Beardlessbrady** [comment]
Okay I managed to do it, very hard to replicate lol. Will work on a fix and upload asap
