### ISSUE TITLE
[1.10.2] Crash when right clicking wallet in offhand

### ISSUE THREAD

**Issue by xXJamieXx** [BeardlessBrady/Currency-Mod#29]
Hi!

Whilst holding the wallet in the offhand (shield slot) the game crashes with the following report:
https://pastebin.com/GW36U3Ds

Thanks!

**Comment by Beardlessbrady** [comment]
Ill look into it soon

**Comment by BeardlessBrady** [comment]
Can you confirm if this is fixed in the newest version?

**Comment by xXJamieXx** [comment]
Did you have an update on this? I noticed an email notification saying you commented but I don't see it anymore?

**Comment by Beardlessbrady** [comment]
Oh, for some reason I thought I fixed it but later realized I hade not yet. Ill put it in the next upcoming patch (next week or 2)

**Comment by Beardlessbrady** [comment]
Sorry I just don't have the time to keep older versions updated with bugfixes. I sincerely apologize.
