### ISSUE TITLE
Using a 1-9 shortcut key to purchase a vending machine item can cause the client to crash

### ISSUE THREAD

**Issue by Xiaoyan366** [BeardlessBrady/Currency-Mod#3]
[crash-2016-12-17_17.41.11-client.txt](https://github.com/BeardlessBrady/Currency-Mod/files/658790/crash-2016-12-17_17.41.11-client.txt)

Use 1-9 shortcuts buy vending machine project will lead to client crashes

Numeric shortcuts appear to function as MouseTweaks-2.6.4-mc1.10.2.jar

Another point
The head of the vending machine project block 
Placed on the ground will crash

**Comment by Beardlessbrady** [comment]
How did you place the head by itself?

**Comment by BeardlessBrady** [comment]
Anywho, those are both easy fixes. Will be fixed in the next update

**Comment by Beardlessbrady** [comment]
You shouldn't be able to place the top of the vending machine as it has no item. So how did you do it?

**Comment by Xiaoyan366** [comment]
Is the creation mode

**Comment by Xiaoyan366** [comment]
Mainly with the number of shortcut keys 1-9 to buy goods client crash

If the vending machine money directly client crashes

**Comment by Beardlessbrady** [comment]
It was an easy fixed. It will be in the next update probably tomorrow or the next day. But yes the top part shouldn't even be placable at all (which is why it crashes)

**Comment by Xiaoyan366** [comment]
Right click will crash
I'll try again

**Comment by Beardlessbrady** [comment]
Ok. What is the issue with the top of the vending machine?

**Comment by Xiaoyan366** [comment]
[crash-2016-12-19_10.58.54-client.txt](https://github.com/BeardlessBrady/Currency-Mod/files/659966/crash-2016-12-19_10.58.54-client.txt)
Top vending machine placed on the ground
Right clicking on it will cause the client to crash

**Comment by Beardlessbrady** [comment]
There isn't an item for the Top of the vending machine, so how are you placing it

**Comment by Xiaoyan366** [comment]
Creative mode
Get through the mouse wheel

**Comment by Beardlessbrady** [comment]
Alright, well this wont possible in the next update
