### ISSUE TITLE
Startup crash [Forge 14.21.0.2231][1.12]

### ISSUE THREAD

**Issue by Beanius** [BeardlessBrady/Currency-Mod#30]
https://gist.github.com/Beanius/b8574f968c45b35e73eedcc2acfd38f4

**Comment by Beardlessbrady** [comment]
What version of the mod?
How did the crash occur (Explain detail)
Can you recreate the issue WITHOUT any other mods?
 If it only persists with mods let me know which ones

**Comment by Beanius** [comment]
Think you only have one 1.12 version on the twitch app.
https://gist.github.com/Beanius/536d12dd7ed6b50068192631a13db714
Crashed with only Good Ol' Currency 1.12.0-1.1.1 and Forge 14.21.0.2333 installed

**Comment by Beanius** [comment]
https://gist.github.com/Beanius/87c9b3e6365cd25eed99894b5b538854 <- Full log

**Comment by Beardlessbrady** [comment]
Alright, I will look into it today

**Comment by Beardlessbrady** [comment]
Should be fixed on 1.1.2 of the 1.12 release
