### ISSUE TITLE
bill bug 

### ISSUE THREAD

**Issue by Tidloas** [BeardlessBrady/Currency-Mod#33]
If there are more than 10,000 dollars in the machines.
And that have done "cash", bug tickets.
In 1.10.2

**Comment by Beardlessbrady** [comment]
Can you explain your issue in more detail please, I don't quite understand.

**Comment by Tidloas** [comment]
If have raised more than 10,000 dollars, in machines (sale, purchase)
Have gotten by using the "cash" button, stack tickets of -128 for example.
At some level, may even duplicate the tickets.
Screen here:
before : https://image.noelshack.com/fichiers/2017/29/3/1500496499-2017-07-19-22-33-55.png
after: https://image.noelshack.com/fichiers/2017/29/3/1500496509-2017-07-19-22-34-23.png

**Comment by Beardlessbrady** [comment]
Ok so are you saying the machine didnt output the right amount of money?

**Comment by Tidloas** [comment]
In fact, the machine works well.
But it does not make multiple stack. And if the sum is too large.
Example: 15,000 dollars in the machine. The machine will not reimburse well.
You can see the screen above. I have a stack of 268 tickets.
Which bug the ticket, because have lost money or duplicate.

**Comment by Beardlessbrady** [comment]
Hey so I am finally able to work on the mod again. So basically your issue here is that the money is stacking over 64? In your example it still gives you the exact amount of money, there is no loss or duplication I can see

**Comment by Beardlessbrady** [comment]
Better explained in report #40
