### ISSUE TITLE
[Resource] es_ES/MX translation

### ISSUE THREAD

**Issue by Dorzar** [BeardlessBrady/Currency-Mod#34]
//Translate by: Dorzar / VeryHardChamp
//Última actualización: 23/07/2017
//Item names
item.modcurrency:banknote_0.name=1 crédito
item.modcurrency:banknote_1.name=5 créditos
item.modcurrency:banknote_2.name=10 créditos
item.modcurrency:banknote_3.name=20 créditos
item.modcurrency:banknote_4.name=50 créditos
item.modcurrency:banknote_5.name=100 créditos
item.modcurrency:wallet.name=Billetera
item.modcurrency:guidebook.name=Guía de créditos para cabezas cuadradas

//Block names
tile.modcurrency:blockvending.name=Máquina expendedora
tile.modcurrency:blockexchanger.name=Máquina de intercambio
tile.modcurrency:blockatm.name=Cajero automático

//Shared Gui Stuff
tile.modcurrency:gui.playerinventory=Inventario

//Buy Sell Gui Stuff
tile.modcurrency:guivending.profit=Lucro
tile.modcurrency:guivending.funds=Fondos
tile.modcurrency:guivending.slotsettings=Conf. de ranura
tile.modcurrency:guivending.cost=Costo:
tile.modcurrency:guivending.amount=Cantidad:
tile.modcurrency:guivending.cash=Efectivo
tile.modcurrency:guivending.infinitestock=Stock infinito
tile.modcurrency:guivending.locktab=Bloquear tab
tile.modcurrency:guivending.bufferjam=¡La ranura de la salida está llena, pon una tolva debajo de la máquina!

//ATM Gui Stuff
tile.modcurrency:guiatm.feesettings=Conf. de ATM
tile.modcurrency:guiatm.fee=Cuota:

**Comment by Beardlessbrady** [comment]
Ill add this in in the next update, thanks!
