### ISSUE TITLE
[1.11.2] Weird Wallet Inventory Bug

### ISSUE THREAD

**Issue by brisingraerowing** [BeardlessBrady/Currency-Mod#36]
For some reason, I often cannot place bills into a wallet, and when they do place, they only place a single bill. This behavior also extends to the inventory below the wallet GUI.

GOC: 1.11.2-1.2.0
Forge: 13.20.1.2393

**Comment by brisingraerowing** [comment]
Update: I found that clicking very close to the center of a slot works, but clicking anywhere else doesn't.

**Comment by Beardlessbrady** [comment]
The wallet GUI has always been finicky. I will look into once I have time again mid August

**Comment by Beardlessbrady** [comment]
Fixed, coming in the next release
