### ISSUE TITLE
[1.12]All of the inventory slots from this mod are very picky about placement.

### ISSUE THREAD

**Issue by dragon3025** [BeardlessBrady/Currency-Mod#37]
Mincraft: 1.12
Forge: 14.21.1.2420
Mod Version: 1.2.0

When placing items in the slots of the Wallet, Vending Machine, and Exchange you have to click in the exact middle of the slot. The item has to be perfectly centered in it, and if it's just a pixel off it wont place. This also happens with the inventory slots of the player when the GUI of the Wallet, Vending Machine, and Exchange Machine is open.

**Comment by Beardlessbrady** [comment]
Ya I've noticed this as well, I now have time to work on the mod again and will be looking into this issue

**Comment by Beardlessbrady** [comment]
Fixed, coming in the next release
