### ISSUE TITLE
[1.12.1, 1.12.2] Problem with big amount of money

### ISSUE THREAD

**Issue by Krosta8** [BeardlessBrady/Currency-Mod#40]
Hello,
I found a problem with transaction of big amount of money.
Example: I wanted to sell 64x diamond block (1 for 5 000) and I got this: https://imgur.com/a/fnHuR

I tried to click "Cash", but nothing happens.
Sometimes after a while I have inventory full of Bills.

If you repair this, there will be another problem. When player has full inventory and sell for more then 6400 Dollars, the money just disappear, because of the full inventory. Can you add "check inventory" or something like that?

Also I thing, that would be fine to add option to config for "max amount per item".

Currency: 1.2.5
Forge: 2486

Thank you,
Krosta8

**Comment by Beardlessbrady** [comment]
Alright, I shall look into this and see if it is reproducible then get back to you

**Comment by Beardlessbrady** [comment]
Alright, I can't seem to reproduce it so:
A) Can you reproduce it, what are the EXACT steps you go through to do so.
B) Is there any sort of crash report that goes along with the bug, server or client side?

**Comment by Krosta8** [comment]
Oh, sorry, I forgot the most important.

It is happened only on server.

I'm using SpongeForge 1.12.2.

Sorry for the misunderstanding

EDIT: Here is GIF for you, better to explain by GIF, than by comment :D
https://imgur.com/a/B9wpx
Another thing, which I found.
When I remove the upper tile of Exchanger it is generating cash :D 
Also I found out, that the money doesn't disappear at all, it is just "invisible". More info is in the second gif. It's look like a problem with inventory updates.
Hope its help.
https://imgur.com/a/4L2Ez

**Comment by Beardlessbrady** [comment]
Alright...now see if you can reproduce it WITHOUT SpongeForge and just Forge. That would help determine the issue

**Comment by Krosta8** [comment]
The problem is on forge too (exactly forge 1.12.2-14.23.0.2491)

**Comment by Beardlessbrady** [comment]
Fixed in the next release, coming out this week sometime
