### ISSUE TITLE
Exchange and vending machine not showing prices

### ISSUE THREAD

**Issue by jugulargrunt** [BeardlessBrady/Currency-Mod#42]
On our server we are looking to use the good ol currency mod, but, when using the machines the item prices are not showing up. 
Is it just us forgetting to change something or is it bugged?
We are playing 1.10.2

**Comment by Beardlessbrady** [comment]
You must be using NEI? (The JEI addon) it seems to mess up my tooltips. Im fairly certain it is fixed in newer versions (1.11.2+). I asked the NEI mod dev to fix it for 1.10 but he didn't want to. Best thing you can do is remove NEI. Sorry
