### ISSUE TITLE
1.12: giving more than 127 hundred dollars in a exchange machine gives no money back

### ISSUE THREAD

**Issue by Akitori** [BeardlessBrady/Currency-Mod#43]
Yeah, friend was messing with a machine and he reported to me that the machine wasn't giving him any money when he tried to exchange greater than 12700 dollars

I tested it, found the limit where it does that, and have a theory as to why. Your machine gives out stack sizes of up to 127 dollars, any greater causes it to error methinks. Can you fix it asap?

**Comment by Beardlessbrady** [comment]
I'm aware of the issue, Will probably push a fix for it in the next week or two

**Comment by Beardlessbrady** [comment]
Fixed in next update.
