### ISSUE TITLE
How to work with exchange machine? [1.10.2]

### ISSUE THREAD

**Issue by slava110** [BeardlessBrady/Currency-Mod#44]
I'm trying to put item in slot and nothing happens. Maybe I'm just too stupid. I don't know.
![2017-10-01_14 58 11](https://user-images.githubusercontent.com/26705162/31054317-f52a3242-a6b8-11e7-86f4-d7f563a7bf3f.png)
P.s.: Sorry for my English, I'm from another country.

**Comment by Beardlessbrady** [comment]
The best thing I can tell you to do is read the Guide book included in the mod.
