### ISSUE TITLE
Wallet Crash

### ISSUE THREAD

**Issue by LiEyWe** [BeardlessBrady/Currency-Mod#45]
I put some money (one 50-dollar bill, one 20-dollar bill and two 1-dollar bills) in my wallet.
https://imgur.com/a/CvZMO
first, the two 1-dollar bills disappeared. They were in the slot highlighted by the cursor. When I try to click on the highlighted slot, I get this crash:
https://pastebin.com/TjBp9sWg

**Comment by Beardlessbrady** [comment]
Question. Did you change the size of the wallet in the configs ? (Client or server side )

**Comment by LiEyWe** [comment]
wallet size is default (4) on both server and client

**Comment by Beardlessbrady** [comment]
Hmm, Ill look into it probably next week, Hopefully have a bugfix released close to then

**Comment by LiEyWe** [comment]
next week lol :D
