### ISSUE TITLE
Dollar Bills as Quest Reward for Better Questing

### ISSUE THREAD

**Issue by D3nnis3n** [BeardlessBrady/Currency-Mod#46]
Hello,
i'd like to give your Dollar-Bills out for Better Questing Quests. But they are the only items Better Questing does not Show in their rewards list to choose. They just aren't in the choosing menu, like all other items are. I'm wondering what could be the reason of this and if you could add compatibility?

Your wallet and the blocks are in there to choose.

**Comment by Beardlessbrady** [comment]
The only thing I can think of is they don't have recipes. That's the only thing different about them. I'll look into it in a couple days

**Comment by D3nnis3n** [comment]
@BeardlessBrady 
I found out that i can use the Dollar Bills when i got some in the inventory. I can only not find them in their list of items manually or by search. Seems like they are - as of some reason - not in this list.

**Comment by D3nnis3n** [comment]
Uh, fixed?

**Comment by Beardlessbrady** [comment]
Oh sorry. I was just clearing older issues out of the log. I wont be doing any mod support for this version of the mod, with the rewrite however it should be fixed.
