### ISSUE TITLE
[Suggestion] Dollar Bundles

### ISSUE THREAD

**Issue by D3nnis3n** [BeardlessBrady/Currency-Mod#47]
As the Dollar seeming to only have a max of 100 Dollar bills - which is not much i would suggest bundles of those notes for better storage capacity. We in Germany e.g. got 200 and 500 € - in order to stick to the Dollar, you could do bundles of 10, 20, 50 or so. At least for us it get's pretty hard to store all the Money. (And as of missing Cents or pennies we Need to have a high range of cost for the materials)

**Comment by Beardlessbrady** [comment]
Hmm, Maybe Ill throw it in the next update.

**Comment by D3nnis3n** [comment]
You could also add Cents, if you liked. Then we could do something like 1 dirt = 0,01 $.

**Comment by Beardlessbrady** [comment]
Might be a better idea. Won't be hard to implement. I think I'd prefer to do that. Which version of the mod are you using? I prefer to keep new content on 1.12+
