### ISSUE TITLE
Bug when you put a big stack of items in the exchange machine - cash value gets negative after crossing 30000 $

### ISSUE THREAD

**Issue by D3nnis3n** [BeardlessBrady/Currency-Mod#48]
I bought Uranium Ore. 99 of it for 800 § each. When placing a stack of 64 it did Count up very fast up to 30000 $, then suddenly put a "-" in front and counted down from -30000$ to somewhat about -14000$

Screenshot:
https://ibb.co/jes9rG

**Comment by Beardlessbrady** [comment]
Yes, I am aware of this odd issue, Looking into it

**Comment by Beardlessbrady** [comment]
Fixed in next release coming this week
