### ISSUE TITLE
[Suggestion] Allow to buy or sell an explicit amount of items for an explicit price

### ISSUE THREAD

**Issue by D3nnis3n** [BeardlessBrady/Currency-Mod#49]
What would help with the Inflation with Money would - next to adding Cents be:
Allow the user to define he sells 64 dirt for 1 Dollar. Or 32 Dirt for 1 Dollar. Or 1 dirt for 1 Dollar.
At the Moment it seems you can only do 1 item = X Dollar. But not X items = X Dollars.

**Comment by Beardlessbrady** [comment]
https://trello.com/b/TIjaFASH/currency
Above is my Trello (Which is linked on the curse forge page). It is in the works for the next big update
