### ISSUE TITLE
Idea - Use a compat from iron backbacks for wallet.

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [BeardlessBrady/Currency-Mod#5]
So I just had a realization Iron backpacks is super popular; what if you made a small addon the could only hold the currency for this mod? That way you could have an easy wallet and it would never interfere with direct wallet or cash counter you would make on the GUI. Also some people hate GUIs I personally love em and can't wait till you make an official change.

**Comment by Beardlessbrady** [comment]
I already have a wallet in mind. Good Idea though
