### ISSUE TITLE
[Suggestion] Allow infinite mode in exchange machine to KEEP the items

### ISSUE THREAD

**Issue by D3nnis3n** [BeardlessBrady/Currency-Mod#50]
I would like to have an option for the items in a Exchange machine in infinite mode to not vanish.

We would like to use it e.g. for buying uranium. This would be paid by the Server, as with the uranium we make energy that every Player in the City can use free of Charge (he pays taxes to the Server city). But they will get some Money for trading it to us. (Sureley US has infinite amount of Money :D)

**Comment by Beardlessbrady** [comment]
I suppose I'll make that the default, seems odd I didnt already.

**Comment by D3nnis3n** [comment]
Sorry, that i spammed you with suggestions. We just tested it and thought what we would like to see. Please ignore any suggestions you don't like :)
