### ISSUE TITLE
[Suggestion] Allow to set the buying amount in Exchange machine to infinite.

### ISSUE THREAD

**Issue by D3nnis3n** [BeardlessBrady/Currency-Mod#51]
At the Moment, even in infinite mode i can not buy infinite items from the players. I can set a value up to 125 as amount, everything above that will make the symbol of the item vanish. We would like to infiniteley buy items from Players (and Keep them and not vanish them) and not refresh the sell every ten minutes *g*

**Comment by Beardlessbrady** [comment]
I believe setting it to 0 should make it infinite?

**Comment by D3nnis3n** [comment]
Wait, i'll try.

**Comment by Beardlessbrady** [comment]
I suppose I should write that in the guide book. Ill add that to my todo list.

**Comment by D3nnis3n** [comment]
Yeh, it is. Sorry. My fault. But you could remove the $ sign in the front of the amount field. :)

**Comment by Beardlessbrady** [comment]
Hey. If you are up to giving me more critisim/ideas for the mod feel free to add me on discord. Would love someone to bounce ideas off of and test versions of the mod so there arent (as many) bugs when I publicly release it. Discord: BeardlessBrady#2909

**Comment by D3nnis3n** [comment]
Are you in MMD Discord?
I've been invited there as i help test MMD Metals Suite.

**Comment by VirtualGaming1** [comment]
@BeardlessBrady I sent you a friend request on Discord if you need some help with some testing including with other mods for 1.12.2
