### ISSUE TITLE
Money does not automatically stack nor enter wallet.

### ISSUE THREAD

**Issue by oddstr13** [BeardlessBrady/Currency-Mod#54]
**Minecraft** 1.12.2
**Forge** 14.23.0.2550
**Good Ol' Currency Mod** 1.12.0-1.2.6

Withdrawing money from `Exchange Machine` `Funds` and `Cash`, `Vending Machine` `Profit` and `Change`
results in money neither stacking nor entering the wallet.
If player inventory is full, money is dropped on the ground, even if there is a wallet, or non-full money stacks in the player inventory.

![2017-11-23_12-51-27](https://user-images.githubusercontent.com/638706/33171707-97daf310-d04d-11e7-9a6b-721a9d64d0e7.gif)

**Comment by Beardlessbrady** [comment]
This is already fixed and will be out in the next release
