### ISSUE TITLE
[Suggestion] Configurable bill names and currency symbol.

### ISSUE THREAD

**Issue by oddstr13** [BeardlessBrady/Currency-Mod#55]
I'm not a huge fan of the use of dollar($) for in-game currencies.
Would've been neat if we could change this in the config file!

![javaw_2017-11-23_13-13-03](https://user-images.githubusercontent.com/638706/33172364-1ab24f20-d050-11e7-80de-797638cafcc5.png)

![javaw_2017-11-23_13-12-48](https://user-images.githubusercontent.com/638706/33172373-201a1f10-d050-11e7-864f-1b3772123840.png)

**Comment by Beardlessbrady** [comment]
To Euros or something like that, I suppose I can add that in.

**Comment by oddstr13** [comment]
I was thinking being able to set the money symbol to what ever you want, same with the names of the items (strings in config file).
`One-Dollar Bill` -> `1 thingymabob`

**Comment by Beardlessbrady** [comment]
Ya thats what I mean. With the Money symbol you can put ONE letter or symbol, the names of items you can already rename in the lang file

**Comment by Beardlessbrady** [comment]
I will try and make the lang file more consistent for the next update, so it includes all text in the mod including the $ symbol

**Comment by oddstr13** [comment]
Please note that some real world currencies use multiple letters, and also place those after the sum.
100kr  vs. $10

**Comment by Beardlessbrady** [comment]
Hmm, unfortunately it seems like too much work to move that around or allow more than one letter.
