### ISSUE TITLE
Pipes not working in 1.10.2

### ISSUE THREAD

**Issue by binary-dragon** [BeardlessBrady/Currency-Mod#56]
Having an issue getting the vending machine to connect to a pipe, clicking the tool tip makes no change. So far I've only tried enderIO Conduits but they don't connect, plus using the wrench on someone elses vending machine causes a client crash and the block to cause crashes from then on until removed with commands.

Had to turn the machine into air to stop it

But the pipe thing isn't working 

I'm running 1.10.2 - 1.1.1

**Comment by Beardlessbrady** [comment]
Ill look into it in a couple days

**Comment by Beardlessbrady** [comment]
Sorry I just don't have the time to keep older versions updated with bugfixes. I sincerely apologize.
