### ISSUE TITLE
Request Baubles Support or Dedicated Wallet slot with hotkey.

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [BeardlessBrady/Currency-Mod#57]
I keep watching this mods progress and I love all the things you have added nice touch using trello. At any rate the last way to make this mod amazing is to do something like add a dedicated wallet slot. Default inventory is just too small when you exceed like 100 mods so its a request not a requirement also you should chat with me sometime Ight peace bro :D

**Comment by Beardlessbrady** [comment]
Ill think about it when I work on the new version :)
