### ISSUE TITLE
Exchange & Vending machines money glitch

### ISSUE THREAD

**Issue by Shiranuit** [BeardlessBrady/Currency-Mod#58]
Minecraft : 1.11.2
Forge 13.20.1.2393
Good Ol' Currency Mod 1.11.2-1.2.2

Mods intalled : Good Ol' Currency Mod

In solo the amount of money that an Exchange & Vending can handle is an Int (32bits)
but when in multiplayer the amount of money that the Exchange & Vending can handle seems to be a
Short (16bits) when above 32767$ the money became negative and the 'Cash' button doesn't work

In solo :
![solo currency](https://user-images.githubusercontent.com/19224148/35532749-a14bae4e-053b-11e8-880f-87ba474e19f6.gif)

In multiplayer : 
![server currency](https://user-images.githubusercontent.com/19224148/35532772-b63448ac-053b-11e8-868e-f1853f470907.gif)

**Comment by Beardlessbrady** [comment]
Yes this has been fixed in the 1.12 version of the mod. Once I get this final update out for the mod (sometime in the week or two) I will be porting it to 1.11.2 and 1.10
