### ISSUE TITLE
Idea Request - Resource Pack "Pokedollars"

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [BeardlessBrady/Currency-Mod#6]
I was wondering since I have no modding talent if you could make a resource pack that turned the money into the poke-dollars like seen here. http://cf.geekdo-images.com/images/pic653317_md.jpg

**Comment by Beardlessbrady** [comment]
Feel free to make that yourself. Its not too difficulty

**Comment by P3rf3ctXZer0** [comment]
Any tips? I have never done anything related to directly modding.

**Comment by Beardlessbrady** [comment]
Its not even modding. You just have to make a resource pack. I'm sure there are some simple tutorials you can find via google
