### ISSUE TITLE
No bills in 1.12.2 mod

### ISSUE THREAD

**Issue by Jkpiotro98** [BeardlessBrady/Currency-Mod#60]
I downloaded the 1.12.2 mod and it runs perfectly but the thing is there's no bills in the game. I took a screen shot of what is available from your mod that i can use. (https://user-images.githubusercontent.com/36071378/35729897-e06a3a32-085b-11e8-9381-19245699d92b.png)

**Comment by Beardlessbrady** [comment]
Check out the Mod's creative mode tab

**Comment by Jkpiotro98** [comment]
I've checked and there's nothing there

**Comment by Beardlessbrady** [comment]
Have you tried the mod in an isolated environment (without other mods)? Bills should appear there. Are you using a specific modpack or a collection of your own mods. It must be another mod messing with it somehow, not much I can do there unfortunately
