### ISSUE TITLE
Suggestion: some sort of FTB utilities enabled land renting system

### ISSUE THREAD

**Issue by GeminiMarshdevil** [BeardlessBrady/Currency-Mod#61]
title says it basically. some sort of block or mechanism that allows me as admin of my server to setup a single or multiple chunks of land for renting.  preferably integrated with FTB utilities land claims so the renter gets to claim the chunk as if part of their own team and then that specific chunk or even all of their claimed chunks gets revoked if they don't pay their rent every so many days. preferably customizable day count but once a month would be fine. 

is this even possible? even if the rent-block just filled the entire chunk with unbreakable airblocks or something and not actually using ftb utilities?

**Comment by Beardlessbrady** [comment]
I like the idea actually. I'll include it in my to-do list for the rewrite
