### ISSUE TITLE
Interest on ATM currency

### ISSUE THREAD

**Issue by Majora320** [BeardlessBrady/Currency-Mod#62]
It would be nice for a creative mode player (the server admin) to be able to set an interest rate for "savings" in ATMs, which combined with ATM fees would add a more real-economy-like aspect to the game.

Example: set a 5% intrest rate per day, plus a $5 withdrawal fee.

**Comment by Beardlessbrady** [comment]
The ATMS were very unfinished, I only released what I had because I plan on rewriting the mod, I will take this into consideration when I work on the ATM's in 2.0 of the mod. Thanks!
