### ISSUE TITLE
[1.12.2] Exchange Eating Items

### ISSUE THREAD

**Issue by ricwi42** [BeardlessBrady/Currency-Mod#63]
Running Forge 1.12.2-2611 and Currency 1.3.1.

When selling items to an exchange, they are disappearing rather than being available in any way to collect.

**Comment by ricwi42** [comment]
Update: When using a 2 unit tall Exchange, the issue seems to be resolved.

**Comment by Beardlessbrady** [comment]
I will hopefully look at this, this coming weekend

**Comment by Beardlessbrady** [comment]
Alright, I know the reason for this. For some reason the 'delete items' option in the infinite tab (only appears to creative players) is on automatically. I will fixed it to be auto off but for the time being you can go into creative and change the option per machine. (Sorry)
