### ISSUE TITLE
[1.12.2] Vending Machine Buffer Accessible to Non-Owner

### ISSUE THREAD

**Issue by ricwi42** [BeardlessBrady/Currency-Mod#64]
If a Vending Machine is set to generate change in any denomination automatically, when it enters the buffer slots, it's visible and able to be picked-up by all players.

This allows a user to make a purchase, and then collect most/all of their money back from the buffer without access to the edit tab.

Running Forge 1.12.2-2611 and Currency 1.3.1.

**Comment by Beardlessbrady** [comment]
I shall look into this, this coming weekend

**Comment by Beardlessbrady** [comment]
Hey ricwi42,

I tested this issue on both client and server and I can't seem to replicate it. Are you running any other mods? Also does the money appear where they usually would or somewhere else on the screen?

**Comment by ricwi42** [comment]
Gah. Sorry dude, my notifications weren't on. I'll look at this again and make a little vid for you if I can replicate. Updating my server atm.

**Comment by ricwi42** [comment]
Hey again!

I was able to replicate the issue. The key that I've found the vending machine has to belong to another player in order to display that behavior. I can't cause the issue with my own vending machine, but other players can and vice versa.

If I access another user's vending machine, I can hover over the left side of the GUI and see the Buffer slots highlight.

For the record, I'm using several other mods. I'll list 'em off if this new info doesn't get you any closer.

Hope that helps!

**Comment by Beardlessbrady** [comment]
SO I am able to replicate part of the issue, I can see the buffer but can't grab any of the items. Are you sure you can grab the items?

**Comment by Beardlessbrady** [comment]
Working on the issue (finally) sorry about the delay, has been a busy 2018

**Comment by Beardlessbrady** [comment]
Fixed, will be included in the next mod release (Coming in the next few days).
