### ISSUE TITLE
Wallet Crash in 1.10.2

### ISSUE THREAD

**Issue by r3volut1on** [BeardlessBrady/Currency-Mod#65]
*Mod Version* 
modcurrency{1.10.2-1.2.2} [Good Ol' Currency Mod]

*Forge*
Forge{12.18.3.2511}

*Description*
When putting change back into the wallet, the dedicated server crashed.

*Crash Report*
https://pastebin.com/rPmnZn8w

**Comment by Beardlessbrady** [comment]
Ill look into it in the next coming week

**Comment by Beardlessbrady** [comment]
Sorry I just don't have the time to keep older versions updated with bugfixes. I sincerely apologize.
