### ISSUE TITLE
[Request] make a config option to change the name of the currency

### ISSUE THREAD

**Issue by winsrp** [BeardlessBrady/Currency-Mod#67]
Currently its dollar this and dollars that, but I would love to name my coin after the server, or something funny, plz!, and maybe another config option of the currency symbol to be used (taken from text)

e.g.

Currency name = "Servercoin"
Currency symbol = "¢"

or something like that.

**Comment by Beardlessbrady** [comment]
Unfortunately I plan on remaking the mod from the ground up. I wish I could focus on upkeep of the 1.0 version as well but seeing as I already have limited time it means I have to leave it as is. 

Fortunately this mean in the 2.0 version people will be able to make their own custom currencies which will obviously include symbolize and naming.

**Comment by winsrp** [comment]
not sure if that is good news or bad news XD, but still its some news. thanks for the reply.
