### ISSUE TITLE
Vending Machine eating items when restocked automatically

### ISSUE THREAD

**Issue by TheJohnLong** [BeardlessBrady/Currency-Mod#69]
With a default vending machine (no upgrades) when attempting to pump in iron ingots to refill the vending machine, items get pushed into the inventory but no new items are available for sale. items pumped in using both vanilla hoppers and ender io conduits have the same result. This happens with both single and double tall vending machines. Found in Foolcraft 3 1.3.

**Comment by Foolcraft3NZ** [comment]
Update: Have figured out how to recreate this.
Have the setup trying to pipe items in, take 2 or more items in a stack, and drag them across like you would to evenly spread them out in a crafting recipe. watch them stack ontop of each other and start over-stacking.

**Comment by Beardlessbrady** [comment]
Unfortunately I have no time currently to work on the mod, but come August I will have all the time in the world.

**Comment by Beardlessbrady** [comment]
I believe Ive fixed this in the mod version coming in the next few days.
