### ISSUE TITLE
[Bug] Dupe bug when buying the same item in multiple slots

### ISSUE THREAD

**Issue by GazbonicAcid** [BeardlessBrady/Currency-Mod#7]
There's a dupe bug when buying the same item in multiple slots.
Though this only happens if you have the same "item" in multiple slots.
If you only have it in one slot, this dupe bug does not happen.
Before Selling a single ingot
http://i.imgur.com/GylT8yg.png
After selling a single ingot
http://i.imgur.com/shVFsRN.png

**Comment by Beardlessbrady** [comment]
Will fix tonight and ship an update asap

**Comment by Beardlessbrady** [comment]
Alright. Releasing update now for this bug
