### ISSUE TITLE
Infinite storage

### ISSUE THREAD

**Issue by nzminecraftDOTcom** [BeardlessBrady/Currency-Mod#70]
When using EnderIO conduits piping items into a basic (max 16 per slot) vending machine, it will store so far an unlimited amount of items, rather than maxing out at 16.
Haven't tried any other types of pipes or input methods.

**Comment by nzminecraftDOTcom** [comment]
Update: Have figured out how to recreate this.
Have the setup trying to pipe items in, take 2 or more items in a stack, and drag them across like you would to evenly spread them out in a crafting recipe. watch them stack ontop of each other and start over-stacking.

**Comment by Beardlessbrady** [comment]
Unfortunately I have no time currently to work on the mod, but come August I will have all the time in the world.

**Comment by Beardlessbrady** [comment]
So unfortunately I wont be integrating with other mods IN THIS VERSION. I plan on working on a complete rewrite of the mod in the near future which will hopefully work with other mods much better.
