### ISSUE TITLE
Opening guy give you some kind of X-Ray sight

### ISSUE THREAD

**Issue by TheRealDadbeard** [BeardlessBrady/Currency-Mod#71]
See here: https://imgur.com/a/QX7ohIO

**Comment by Beardlessbrady** [comment]
Alright so I need a little more information than that. First off what version of the mod are you using and what version of forge?

Secondly, obviously you are using other mods, could you help me pinpoint which mods could be causing that behavior? Get it down to as small as a list as you can that would be great.

**Comment by TheRealDadbeard** [comment]
Yeah sorry about that.

MC: 1.12.2
Forge 2750
GoodOlCurrency: 1.3.2

Heres a list of my mods installed, I have no idea which one could cause it and did't came around testing mods through but will if you can pinpoint the issue. That link is in fact a crashlog but theres a list of mods there, just ignore everything else. 

https://paste.dimdev.org/ipowukayiy.mccrash

If I have time later i will test what could cause it.

**Comment by TheRealDadbeard** [comment]
Okay so I could pinpoint it to Fast Render in Optifine

**Comment by Beardlessbrady** [comment]
Ok so optifine is notorious for breaking all the things but I will try my best to fix it. No promises

**Comment by TheRealDadbeard** [comment]
Thanks. I Just disabled fast render for now
