### ISSUE TITLE
NPE rendering screen

### ISSUE THREAD

**Issue by ghost** [BeardlessBrady/Currency-Mod#72]
Minecraft 1.12.2
Forge 14.23.4.2705
mod Currency 1.12.0-1.3.2

Expected behaviour:
Display page.

Actual behaviour:
Null pointer exception.

Steps: 
Open the "currency for blockhead" book on atm pages.

log:
https://pastebin.com/wEXEc0r8

**Comment by Beardlessbrady** [comment]
Hey, sorry I took so long I am finally able to get into bug squishing. So I tried the version of the mod and forge specified and I was able to read through the book fine. The issue must be with another mod you are using.  Do you think you can pin point which mods could be causing the issue?

**Comment by ghost** [comment]
the modpack is foolcraft 3 (avalable on twitch launcher).
I tried to launch mods by mods with your mod but no crash happen.
The issue happen when i run the full modpack.

**Comment by Beardlessbrady** [comment]
But it happens every time?  I'll look into it
