### ISSUE TITLE
[Suggestion] Add Amount in wallet display 

### ISSUE THREAD

**Issue by UnRealDinnerbone** [BeardlessBrady/Currency-Mod#73]
Add a number in the top right of wallet GUI showing how much money is in the wallet

**Comment by Beardlessbrady** [comment]
Good idea. Im working on a 2.0 of the mod and Ill be sure to add that in when the times comes.

**Comment by Beardlessbrady** [comment]
Although I don't plan on adding any new features to the 1.0 version since its so small I will. Will be in the next release

**Comment by Beardlessbrady** [comment]
Added in the 1.3.6 release (which is out now)
