### ISSUE TITLE
Recipes...

### ISSUE THREAD

**Issue by P3PSIE** [BeardlessBrady/Currency-Mod#75]
Im currently playing through FTB Sky Adventures, and they have included this mod as a big part of the pack. But the recipes for things are driving me mad. I know it would be alot of work but you need to have shapeless recipes at least! The one for a $5 note is a nightmare! Also using the correct denominations of coins and notes to make bigger ones doesnt seem to work alot of the time, i.e.;

*      *        *
*     25c    25c      this should produce a $1 note, but it doesnt do anything at the moment.
*     25c    25c

^^^
Crafting grid with four 25 cent coins.

This is just one example of using the correct denominations but it not working, and it makes using the mod very cumbersome. 

I am really liking the mod and what FTB have done with it, but as a feedback note the recipes are hard work!

Thanks

**Comment by Beardlessbrady** [comment]
I plan on changing the recipes and I appreciate you coming here with feedback. Thanks!

As for my mod being a big part of the pack.   They disabled everything but the currency items lol which means they basically disabled the main meat of the mod. But I'm glad you are enjoying the mod (minus the head ache).
