### ISSUE TITLE
capacity?

### ISSUE THREAD

**Issue by Nitess** [BeardlessBrady/Currency-Mod#77]
Could you make a wallet with a larger capacity? Maybe a bank card? And a new ATM, where you can replenish and withdraw the balance. I want to make my modpack, and I want to use large sums of money to buy and sale. And all this is a wallet that can hold 36 stacks. Where to put a million? With three four wallets to take turns to get money from them and throwing money at an ATM is not very convenient. Or banknotes more than 250 500 1000?

**Comment by Beardlessbrady** [comment]
We will see in the 2.0 version I have cooking up, I have a few ideas.

**Comment by Beardlessbrady** [comment]
I have some plans in the 2.0 version :)
