### ISSUE TITLE
Exchange machine not working

### ISSUE THREAD

**Issue by Corncck** [BeardlessBrady/Currency-Mod#78]
When trying to setup items in the Exchange machine, I will often have a full inventory of items I've entered to sell later, and I will have gone through and entered prices for each item, but when I close out and try to reopen the machine, all of the items are gone. I've noticed though that when you mouseover the items before closing out, the machine will tell you in 'slot settings' (where you edit the price) that the item id is [no item]. I'm not sure if this is a user error or a mod error, but I find the issue really annoying.
![image](https://user-images.githubusercontent.com/46585607/51011674-6c83de00-1527-11e9-9e93-7a08192115a9.png)

**Comment by Beardlessbrady** [comment]
Are you able to recreate this issue with no other mods present. Let me know :)

**Comment by Corncck** [comment]
hi! so disabling all mods except for the forge ones does not solve the issue, its still exactly the same. Hope this helps! :)

**Comment by Beardlessbrady** [comment]
Yes thank you, will look into it hopefully soon!

**Comment by Corncck** [comment]
Any progress on the issue, yet? Just curious @BeardlessBrady

**Comment by Corncck** [comment]
lmao sorry- i thought close meant close the comments

**Comment by Beardlessbrady** [comment]
Sorry, I am no longer working on the 1.0 version. Putting all my free attention on the rewrite.
