### ISSUE TITLE
Crash when using number keys to move wallet around

### ISSUE THREAD

**Issue by ViciousVinnyD** [BeardlessBrady/Currency-Mod#79]
Mouse over an empty slot in your inventory and press the number key that the wallet is located and the game crashes.

Time: 1/18/19 12:38 AM
Description: Updating screen events

java.lang.NullPointerException: Updating screen events
	at gunn.modcurrency.mod.container.util.INBTInventory.writeInventoryTag(INBTInventory.java:25)
	at gunn.modcurrency.mod.container.ContainerWallet.func_184996_a(ContainerWallet.java:139)
	at net.minecraft.client.multiplayer.PlayerControllerMP.func_187098_a(PlayerControllerMP.java:566)
	at net.minecraft.client.gui.inventory.GuiContainer.func_184098_a(GuiContainer.java:638)
	at net.minecraft.client.gui.inventory.GuiContainer.func_146983_a(GuiContainer.java:671)
	at net.minecraft.client.gui.inventory.GuiContainer.func_73869_a(GuiContainer.java:648)
	at net.minecraft.client.gui.GuiScreen.func_146282_l(GuiScreen.java:558)
	at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:512)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1759)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1098)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:398)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at gunn.modcurrency.mod.container.util.INBTInventory.writeInventoryTag(INBTInventory.java:25)
	at gunn.modcurrency.mod.container.ContainerWallet.func_184996_a(ContainerWallet.java:139)
	at net.minecraft.client.multiplayer.PlayerControllerMP.func_187098_a(PlayerControllerMP.java:566)
	at net.minecraft.client.gui.inventory.GuiContainer.func_184098_a(GuiContainer.java:638)
	at net.minecraft.client.gui.inventory.GuiContainer.func_146983_a(GuiContainer.java:671)
	at net.minecraft.client.gui.inventory.GuiContainer.func_73869_a(GuiContainer.java:648)
	at net.minecraft.client.gui.GuiScreen.func_146282_l(GuiScreen.java:558)
	at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:512)

-- Affected screen --
Details:
	Screen name: gunn.modcurrency.mod.client.gui.GuiWallet

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityPlayerSP['viciousvinny'/47579660, l='MpServer', x=5.39, y=80.00, z=182.61]]
	Chunk stats: MultiplayerChunkCache: 169, 169
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: World: (184,64,56), Chunk: (at 8,4,8 in 11,3; contains blocks 176,0,48 to 191,255,63), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 11707443 game time, 10128705 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Forced entities: 83 total; [EntityOtherPlayerMP['kyledriver16'/48527127, l='MpServer', x=190.27, y=76.00, z=0.90], EntityPlayerSP['viciousvinny'/47579660, l='MpServer', x=5.89, y=80.00, z=181.52], EntityPlayerSP['viciousvinny'/47579660, l='MpServer', x=5.39, y=80.00, z=182.61], EntityCow['Cow'/50795524, l='MpServer', x=30.89, y=72.00, z=218.46], EntityOtherPlayerMP['RamenAndRice'/47904109, l='MpServer', x=228.08, y=58.92, z=-233.54], EntityCow['Cow'/50795523, l='MpServer', x=37.79, y=72.00, z=211.42], EntityOtherPlayerMP['JaredMiner'/49620287, l='MpServer', x=184.02, y=76.56, z=-19.37], EntityCow['Cow'/50795522, l='MpServer', x=36.22, y=75.00, z=216.55], EntityCow['Cow'/51179524, l='MpServer', x=10.51, y=72.00, z=133.86], EntityOtherPlayerMP['kyledriver16'/48527127, l='MpServer', x=190.27, y=76.00, z=0.90], EntityOtherPlayerMP['E_Stuffs'/36897118, l='MpServer', x=80.76, y=83.08, z=96.48], EntityOtherPlayerMP['Rykziz'/49009019, l='MpServer', x=280.44, y=69.18, z=-158.70], EntityOtherPlayerMP['E_Stuffs'/36897118, l='MpServer', x=14.07, y=92.00, z=187.97], EntityOtherPlayerMP['E_Stuffs'/36897118, l='MpServer', x=146.82, y=71.00, z=-92.39], EntityCow['Cow'/50793233, l='MpServer', x=-5.45, y=80.00, z=182.83], EntityOtherPlayerMP['RamenAndRice'/47904109, l='MpServer', x=187.18, y=74.00, z=50.04], EntityZombie['Zombie'/51237166, l='MpServer', x=79.50, y=18.00, z=219.50], EntityOtherPlayerMP['kyledriver16'/48527127, l='MpServer', x=190.27, y=76.00, z=0.90], EntitySkeleton['Skeleton'/51237162, l='MpServer', x=80.50, y=18.00, z=228.50], EntityOtherPlayerMP['E_Stuffs'/36897118, l='MpServer', x=151.75, y=72.00, z=-89.32], EntityOtherPlayerMP['Rykziz'/49009019, l='MpServer', x=168.59, y=76.00, z=-25.80], EntityOtherPlayerMP['Rykziz'/49009019, l='MpServer', x=193.00, y=81.22, z=-29.65], EntityOtherPlayerMP['E_Stuffs'/36897118, l='MpServer', x=149.85, y=71.00, z=-92.37], EntityOtherPlayerMP['JokersBullet12'/48118346, l='MpServer', x=205.59, y=63.92, z=39.73], EntityOtherPlayerMP['kyledriver16'/48527127, l='MpServer', x=190.27, y=76.00, z=0.90], EntityCreeper['Creeper'/51244602, l='MpServer', x=-72.50, y=21.00, z=122.50], EntityCow['Cow'/50782015, l='MpServer', x=11.45, y=72.00, z=136.45], EntityCow['Cow'/51133493, l='MpServer', x=-13.55, y=87.00, z=176.61], EntityOtherPlayerMP['E_Stuffs'/36897118, l='MpServer', x=236.47, y=63.50, z=-211.00], EntityOtherPlayerMP['kyledriver16'/48527127, l='MpServer', x=190.27, y=76.00, z=0.90], EntityOtherPlayerMP['Hickawa'/47879614, l='MpServer', x=153.87, y=79.87, z=-64.13], EntityZombie['Zombie'/51233359, l='MpServer', x=82.50, y=20.00, z=257.50], EntityOtherPlayerMP['RamenAndRice'/47904109, l='MpServer', x=220.17, y=69.47, z=-80.65], EntityOtherPlayerMP['Rykziz'/49009019, l='MpServer', x=250.23, y=64.33, z=-110.60], EntitySkeleton['Skeleton'/51238725, l='MpServer', x=-55.50, y=16.00, z=177.50], EntityCow['Cow'/50791758, l='MpServer', x=-12.47, y=80.00, z=172.43], EntityZombie['Zombie'/51241028, l='MpServer', x=-6.50, y=37.00, z=213.50], EntitySkeleton['Skeleton'/51238727, l='MpServer', x=-59.50, y=16.00, z=174.50], EntitySkeleton['Skeleton'/51241031, l='MpServer', x=4.50, y=27.00, z=145.50], EntitySkeleton['Skeleton'/51238726, l='MpServer', x=-58.50, y=16.00, z=173.50], EntityCreeper['Creeper'/51243357, l='MpServer', x=74.50, y=24.00, z=104.50], EntityBat['Bat'/51244637, l='MpServer', x=80.34, y=25.01, z=150.09], EntityZombie['Zombie'/51243356, l='MpServer', x=75.50, y=24.00, z=104.50], EntityCow['Cow'/50788190, l='MpServer', x=-16.13, y=86.00, z=175.49], EntityOtherPlayerMP['Hickawa'/47879614, l='MpServer', x=169.38, y=80.00, z=-51.08], EntityOtherPlayerMP['E_Stuffs'/36897118, l='MpServer', x=151.46, y=71.00, z=-90.96], EntityOtherPlayerMP['RamenAndRice'/47904109, l='MpServer', x=185.96, y=74.00, z=45.81], EntityBat['Bat'/51240813, l='MpServer', x=-24.49, y=21.10, z=206.75], EntityOtherPlayerMP['E_Stuffs'/36897118, l='MpServer', x=77.79, y=70.64, z=102.87], EntityBat['Bat'/51233644, l='MpServer', x=22.68, y=26.03, z=103.39], EntityOtherPlayerMP['JokersBullet12'/48118346, l='MpServer', x=163.15, y=78.03, z=14.93], EntityOtherPlayerMP['Vince_Fearne'/47915666, l='MpServer', x=82.86, y=89.11, z=161.41], EntityOtherPlayerMP['E_Stuffs'/36897118, l='MpServer', x=152.22, y=71.00, z=-90.60], EntitySkeleton['Skeleton'/51229047, l='MpServer', x=68.48, y=29.00, z=175.21], EntityOtherPlayerMP['kyledriver16'/48527127, l='MpServer', x=190.27, y=76.00, z=0.90], EntityCow['Cow'/51137153, l='MpServer', x=37.08, y=75.00, z=216.48], EntityBat['Bat'/51221406, l='MpServer', x=77.36, y=18.42, z=154.25], EntityOtherPlayerMP['E_Stuffs'/36897118, l='MpServer', x=14.50, y=88.47, z=178.50], EntityOtherPlayerMP['E_Stuffs'/36897118, l='MpServer', x=145.36, y=71.00, z=-91.85], EntityBat['Bat'/51155345, l='MpServer', x=-74.55, y=19.12, z=111.91], EntityCreeper['Creeper'/51155346, l='MpServer', x=-67.50, y=36.00, z=122.50], EntityOtherPlayerMP['E_Stuffs'/36897118, l='MpServer', x=148.73, y=71.00, z=-92.22], EntityPlayerSP['viciousvinny'/47579660, l='MpServer', x=6.12, y=80.00, z=183.43], EntityOtherPlayerMP['Hickawa'/47879614, l='MpServer', x=151.08, y=78.94, z=-64.47], EntityOtherPlayerMP['Hickawa'/47879614, l='MpServer', x=161.83, y=67.94, z=-68.07], EntityCreeper['Creeper'/51185597, l='MpServer', x=25.50, y=41.00, z=260.50], EntityBat['Bat'/51150269, l='MpServer', x=-74.08, y=20.02, z=109.26], EntitySheep['Sheep'/51135930, l='MpServer', x=12.48, y=71.00, z=115.76], EntityOtherPlayerMP['RamenAndRice'/47904109, l='MpServer', x=237.34, y=63.00, z=36.50], EntityCow['Cow'/50786252, l='MpServer', x=14.20, y=74.00, z=133.60], EntitySkeleton['Skeleton'/51237081, l='MpServer', x=46.50, y=25.00, z=178.50], EntitySkeleton['Skeleton'/51237080, l='MpServer', x=46.05, y=24.00, z=175.95], EntityZombie['Zombie'/51095534, l='MpServer', x=80.50, y=19.00, z=235.50], EntityOtherPlayerMP['E_Stuffs'/36897118, l='MpServer', x=152.38, y=72.17, z=-90.87], EntityPlayerDummy['unknown'/72683, l='MpServer', x=5.39, y=80.00, z=182.61], EntityOtherPlayerMP['Rykziz'/49009019, l='MpServer', x=235.69, y=71.00, z=-10.40], EntityOtherPlayerMP['kyledriver16'/48527127, l='MpServer', x=190.27, y=76.00, z=0.90], EntityOtherPlayerMP['Rykziz'/49009019, l='MpServer', x=286.87, y=81.46, z=-158.27], EntityOtherPlayerMP['E_Stuffs'/36897118, l='MpServer', x=231.13, y=62.92, z=-233.53], EntityZombie['Zombie'/51193083, l='MpServer', x=29.50, y=63.00, z=102.50], EntityBat['Bat'/51185396, l='MpServer', x=-74.00, y=38.32, z=256.22], EntityPlayerSP['viciousvinny'/47579660, l='MpServer', x=5.28, y=80.00, z=181.00], EntityOtherPlayerMP['RamenAndRice'/47904109, l='MpServer', x=230.49, y=62.35, z=-234.30]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:532)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2741)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:419)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

**Comment by Beardlessbrady** [comment]
Ya that makes sense. Ill fix it for the next update Im putting out soon
