### ISSUE TITLE
[Bug / Feature Request] Can't buy items that don't stack

### ISSUE THREAD

**Issue by GazbonicAcid** [BeardlessBrady/Currency-Mod#8]
You can't buy items that don't stack.
I'd like to request the ability to do so.
Possibly have either a separate inventory in the "stock mode" gui where it actually stores items bought.
Instead of storing bought items in the slot players place the item they want to buy.

**Comment by Beardlessbrady** [comment]
I have a plan to fix this. Ill have it out in 2 updates from now

**Comment by Beardlessbrady** [comment]
For the time being I will just make it so you can have an output just under the machine. Should be out in the next few days

**Comment by Beardlessbrady** [comment]
Alright I am going to fix this by adding 'buffer' slots to the side of the GUI. If an Item sold can't fit in the normal slots it will go there. Then you can put a hopper underneath the Exchange machine, allowing you to pump out all but one item in the normal slots and all the buffer slot items.

I will also implement this into the Vending Machine, so if you want you can pump out the money you receive from the buffer.

Lastly I will allow items to be pumped into the back side of the Vending Machine to stock up the items.

I will start work on this tomorrow and will release as soon as I can
