### ISSUE TITLE
Request - Item Sell Block

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [BeardlessBrady/Currency-Mod#81]
So basically I want a recycling block that more or less gives a set about of money for any item thrown in. It would make some things easier to manage and unlike trash you could make money while cleaning clutter.

**Comment by Beardlessbrady** [comment]
Ah yes, you mentioned this before. Ill add it to my todo list.

**Comment by P3rf3ctXZer0** [comment]
How have things been by the way - not to get off topic.

**Comment by Beardlessbrady** [comment]
Pretty good. If you want you can join my discord I started awhile ago for the mod: https://discordapp.com/invite/kSRXwZJ
