### ISSUE TITLE
Purchaseable items showing as red, unaffordable items showing in green.

### ISSUE THREAD

**Issue by katubug** [BeardlessBrady/Currency-Mod#84]
Hi! I'm not sure if this has been reported. When a wallet containing currency is placed into a vending machine, items that can be afforded have their names in red, and the ones that can't be afforded have their names in green. I'm reporting it because that seems opposite of intended behaviour.

Thanks again for the great mod!

**Comment by Beardlessbrady** [comment]
Yes it should be the opposite...how odd.
