### ISSUE TITLE
Single dollar bills don't spend properly when in the wallet.

### ISSUE THREAD

**Issue by katubug** [BeardlessBrady/Currency-Mod#85]
So, I'm working with your mod and the mod Bountiful. Bountiful rewards players for doing various tasks by giving them customizable rewards, and I want to reward them with cash. So the way I've been doing it is having it grant them "modcurrency:banknote" because that seems to be the only way. However, that gives One Dollar Bills, which don't craft into higher bills. So I was putting them in my wallet and just dealing with it.

However, when I finally earned enough to afford an item worth $500 and went to buy it, it didn't charge me properly. I don't remember the exact amount, but I had ~$300 left.

When I went to go test it just now, with only One Dollar Bills in my wallet, it doesn't deduct anything at all - just gives me the item and lets me keep my balance.

For now I'm just hoping my players don't find out. xD

**Comment by Beardlessbrady** [comment]
will push out a fix tomorrow. thanks!
