### ISSUE TITLE
[SUGGESTION] Reverse profit value selection order

### ISSUE THREAD

**Issue by DevTimur** [BeardlessBrady/Currency-Mod#86]
Hi.
When you click "STOCK" button, and want to recieve "profit" money back. This button
![image](https://user-images.githubusercontent.com/22171136/56343025-4d4dba00-61c2-11e9-9c14-dcfbb9e52fdd.png)
You have this little button sellecting currency you want to get.
I want to recommend to make it sligtly different. Start from highest nominal ($100) and decrease it instead of increasing (100=>50=>20=>10=> etc.) That way you will always get highest nominal first, and then the rest of small money.
Also, i would recomment to revert it back to $100 every time you re-open "STOCK" tab, so you always wtart with highest nominal.

**Comment by Beardlessbrady** [comment]
I agree, that does make more sense
