### ISSUE TITLE
[SUGGESTION] Wallet shuffle

### ISSUE THREAD

**Issue by DevTimur** [BeardlessBrady/Currency-Mod#87]
Can you make so every time you open wallet all your small coins/papers will automatically convert to higher forms.
Instead of this
![image](https://user-images.githubusercontent.com/22171136/56343589-d7e2e900-61c3-11e9-809a-ec7a1474b248.png)
You get this
![image](https://user-images.githubusercontent.com/22171136/56343649-fcd75c00-61c3-11e9-9c0e-6bdadbb08c88.png)
AUTOMATICALLY

**Comment by DevTimur** [comment]
And yes, i know you can fiddle with vending machine. But i would like to see it automated :-)

**Comment by Beardlessbrady** [comment]
I plan to add a more dynamic wallet, itll be an upgrade to the original
