### ISSUE TITLE
Issue with Wallet Balance correctly deducting.

### ISSUE THREAD

**Issue by katubug** [BeardlessBrady/Currency-Mod#89]
I've had this issue occasionally but could never seem to reliably replicate it. Today I received the following report from one of my players:

> OKAY SO
> My wallet has 19k in it
> I went to the luxury, and started shift-clicking the reward bag drei
> ..it lets me grab out as many as I like. It doesn't deduct anything from my wallet.
> So I decided to shift-click the hippogryph egg.
> ..same thing.
> ..in fact never mind uh apparently it just won't take any money out of my wallet whatsoever
> I just took out 74 nether stars. Nothing.
> yep, seems to be anything that costs four digits or more, with at least five digits in teh wallet. Emeralds from the store cost me money, the witherless rose didn't

Unfortunately I don't know what was in his wallet, but I can guarantee that it was all recently obtained because he's a new player (so it wouldn't be the deprecated $1 bill).

**Comment by Beardlessbrady** [comment]
Lol this wallet just hates me. I will look into it Tuesday!

**Comment by Beardlessbrady** [comment]
Hmm, I am unable to recreate this issue even when the cost is 5 digits. Are you able to reproduce it?

**Comment by katubug** [comment]
Okay, testing. My wallet contains $19,200 in $100 bills. I have a Vending Machine set up with an item for $1, $10, $100, $1,000, $10,000, and just for fun, $100,000.

$1 - Deducts properly.
$10 - Deducts properly.
$100 - Deducts properly.
$1000 - Deducts properly.
$10000 - Deducts properly
$100000 - Cannot buy.

Testing again with different denominations: Have $24832 in bills of all denominations, plus $1 and $2 coins.

$1 - Deducts properly.
$10 - Deducts properly.
$100 - Does not deduct.
$1000 - Does not deduct.
$10000 - Does not deduct.
$100000 - Cannot buy.

Okay. Looks like I'm gonna need to break this down by bill type. Give me a bit to test and get back to you.

**Comment by katubug** [comment]
Wallet full of $1 coins, total of $2304.

$1 - Deducts properly.
$10 - Deducts properly.
$100 - Deducts properly.
$1000 - Deducts properly.
$10000 - Cannot buy.
$100000 - Cannot buy.

Wallet full of $2 coins, total of $4608.

$1 - Deducts properly? (see below), but also for some reason causes $1 coins to pop out of the vending machine and land in my inventory? What? lol. Update: It stopped after 3. I'm baffled.
$10 - Deducts properly.
$100 - Deducts properly.
$1000 - Deducts properly.
$10000 - Cannot buy.
$100000 - Cannot buy.

Wallet full of $5 bills, total of $11520.

$1 - Deducts $5 from my total and gives me two $2 coins in return. I wasn't paying attention with the previous wallet, but I'm going to guess it's the same thing? Doesn't seem to be stopping like last time. Update: it did stop after I bought something else and returned to buy more. That's what happened with the previous time as well.
$10 - Deducts properly.
$100 - Deducts properly.
$1000 - Deducts properly.
$10000 - Cannot buy.
$100000 - Cannot buy.

Wallet of $10 bills, total of $21120.

$1 - Deducts properly.
$10 - Deducts properly.
$100 - Deducts properly.
$1000 - Deducts properly.
$10000 - Deducts properly.
$100000 - Cannot buy.

Wallet of $20 bills, total of $21760.

$1 - Deducts properly.
$10 - Deducts properly.
$100 - Deducts properly.
$1000 - Deducts properly.
$10000 - Deducts properly.
$100000 - Cannot buy.

Wallet of $50 bills, total of $22400.

$1 - Deducts properly.
$10 - Deducts properly.
$100 - Deducts properly.
$1000 - Deducts properly.
$10000 - Deducts properly.
$100000 - Cannot buy.

Wallet of $100 bills, total of $25600.

$1 - Deducts properly.
$10 - Deducts only $6.
$100 - Deducts properly.
$1000 - Deducts properly.
$10000 - Deducts properly.
$100000 - Cannot buy.

Hopefully this helps! Let me know if you'd like me to do any other specific tests.
