### ISSUE TITLE
custom currency (additional suggestion for trello)

### ISSUE THREAD

**Issue by xyberviri** [BeardlessBrady/Currency-Mod#91]
I was reading over the custom currency on trello https://trello.com/c/hauKNqzD/92-customization-currency and noted the implementation is going to be "provide textures for these currencies"

would it be possible to also add the ability to just specify an item:metadata and currency value so that you can use items from other mods as money.

That would let me do crazy things like use elements and chemicals from alchemistry as money "<alchemistry:element:1>" so im using helium as my lowest denomination of currency.  

I could play this with Pam's Harvest Craft and use seeds and food as money, or even the fishing mod that adds a bunch of unique fish. 

incidentally that also would resolve issues with the multiple other mods that have some form of currency already implemented and a user wants to use one over another, even a mix.. heck that sort of also implements an exchange.  (when i lived in south Texas everyone accepted both American dollars and Mexican pesos") 

in any case love the mod keep up the awesome work.

**Comment by Beardlessbrady** [comment]
Hmm that would involve some pretty extensive changes to how the currency system works. Why not just setup an exchange machine for those particular items? So you could do "INSERT ITEM" -> CURRENCY VALUE?

**Comment by Beardlessbrady** [comment]
But I will certainly look into this to see if its plausible. If you want to talk more about it come over to my discord: https://discord.gg/kSRXwZJ
