### ISSUE TITLE
Items not appearing in FTB Quests properly

### ISSUE THREAD

**Issue by katubug** [BeardlessBrady/Currency-Mod#94]
Hey, I'm setting up a pack shop using FTB Quests, and discovered that none of the actual money items show up as options to be selected. The wallet does, though. I asked in the FTB Quests discord, and they suggested a workaround (put money in inventory, select items that way), but I thought it would be worth mentioning in case it's something you'd like to fix for the future.

They suggested this line as being part of the problem: https://github.com/BeardlessBrady/Currency-Mod/blob/master-2-1.12/src/main/java/beardlessbrady/modcurrency/item/ItemCurrency.java#L57

To quote, `This should be if(isInCreativeTab(modTab)) or smth`. I personally am out of my depth but I'll happily be a messenger if it helps.

**Comment by Beardlessbrady** [comment]
Ah thanks, I will fix that now for you :P

**Comment by LatvianModder** [comment]
You also should add setCreativeTab(ModCurrency.tabCurrency); in your item constructors

**Comment by Wizardon777** [comment]
Hi.
it doesnt seem to fix the problem yet.
any progress?

**Comment by Beardlessbrady** [comment]
Unfortunately I haven't had time to work on the mod so no, there has been no progress
