### ISSUE TITLE
Blocks going crazy when opening vending machine

### ISSUE THREAD

**Issue by Naeso** [BeardlessBrady/Currency-Mod#95]
Hello,

first, my list of mods : 
ArchitectureCraft, 
AutoRegLib, 
Biomes O' Plenty, 
BlackThorne Civilian Vehicles, 
Coffee Spawner, 
CreativeCore, 
CreativeCoreDummy, 
Decocraft, 
Display, 
Dynmap, 
Effortless Building, 
Elevator Mod, 
Fex's Alphabet & More Mod, 
Galacticraft Core, 
Galacticraft Planets, 
Good Ol' Currency Mod, 
Immersive Vehicles (formerly MTS), 
InControl, 
JurassiCraft, 
Just a Few Fish, 
LLibrary, 
MTS Official Vehicle Pack, 
MalisisCore, 
MalisisDoors, 
Micdoodle8 Core, 
Moonspire Metropolitan Motors Pack, 
MorePlayerModels, 
OnlinePictureFrame, 
OpenComputers,  
Phosphor Lighting Engine, 
Placeable Items Mod, Quark, 
RC Roads, 
RandomPatches, 
Soviet Mod, 
Surge, 
UNU Parts Pack, 
VanillaFix, 
Varied Commodities, 
Waddles, 
2Fexcraft Common Library

My config : 
8gb RAM (6 allowed to MC)
3,4 Ghz processor (4 cores)
128 SSD
Ubuntu server with LXDE as UI

![bug](https://imgur.com/E1U5AvD.png)

So the issue is, as you may see in this screenshot, every block goes comptely crazy when I'm using the vending machine. I can see thought every block !

**Comment by Beardlessbrady** [comment]
Can you reproduce this issue with JUST good ol' currency installed? If not, there is another mod causing the issue and it would be great if you could isolate which one.

**Comment by nift4** [comment]
Maybe Phosphor or VanillaFix
