### ISSUE TITLE
Automatic Refilling still eats items

### ISSUE THREAD

**Issue by mtulepkaliev** [BeardlessBrady/Currency-Mod#96]
The vending machine, when stocked with a hopper, takes the items out of  the hopper but they do not show up in the sales  inventory, same issue as #69 but the issue persists on the latest version(1.12-1.3.11),

Edit:It fills up the first slot just fine but eats the items after the first slot is full
Thanks

**Comment by Beardlessbrady** [comment]
I am no longer supporting version 1.0 as to put my full attention to 2.0. I am thankful for your bug reporting and hope you continue to do report once you are playing 2.0
