### ISSUE TITLE
Vending and exchange machines showing incorrect prices

### ISSUE THREAD

**Issue by Dimentive** [BeardlessBrady/Currency-Mod#99]
Once I had a few items in a vending machine, whenever I added more, the latest item I added didn’t work properly for other players. For me, it was fine, but for other players, the price of that item was displayed as $0. Pretty sure it was just a visual bug, but it was still pretty irritating. It also messed with the price of another item, changing something that cost $30 to $100, seemingly borrowing the price of one of the other items. This is just a visual bug, though. The prices aren’t actually changed, but it is still irritating.

A workaround to this is adding a random item to the vending machine, pricing it, and removing it from the machine.

This same bug happens to exchange machines as well.

I was playing with one friend over LAN.

****

Mod version: 1.3.11 (latest as of right now)
Forge version: 1.12.2-14.23.5.2847
Minecraft version: 1.12.2
Modpack: Heavily modified [Enigmatica 2](https://www.curseforge.com/minecraft/modpacks/enigmatica2/files/2832000)

**Comment by Dimentive** [comment]
Also, I often can’t put things in exchange machines, items frequently appear as buying for $0 which seemingly can’t be fixed. Real annoying.

**Comment by Beardlessbrady** [comment]
How odd, I have never heard of that. Although I am glad you are posting bugs I am no longer supporting the 1.0 version so I can put my full attention onto 2.0. I do appreciate your bug reports though! So when you start playing 2.0 please continue this practice, thank you!

**Comment by Dimentive** [comment]
No worries. I’m really excited for 2.0!
